Repository OCA/account-payment, pull requests merged in 2019-06, with the labels that each got.

#255 [MIG][11.0] account_payment_batch_process
  account_payment_batch_process/README.rst
  account_payment_batch_process/__init__.py
  account_payment_batch_process/__manifest__.py
  account_payment_batch_process/i18n/account_payment_batch_process.pot
  account_payment_batch_process/i18n/pt.po
  account_payment_batch_process/models/__init__.py
  account_payment_batch_process/models/account_payment.py
  account_payment_batch_process/readme/CONTRIBUTORS.rst
  account_payment_batch_process/readme/DESCRIPTION.rst
  account_payment_batch_process/readme/USAGE.rst
  account_payment_batch_process/static/description/icon.png
  account_payment_batch_process/static/description/index.html
  account_payment_batch_process/views/invoice_view.xml
  account_payment_batch_process/wizard/__init__.py
  account_payment_batch_process/wizard/invoice_batch_process.py
  account_payment_batch_process/wizard/invoice_batch_process_view.xml
Labels: approved, needs review

#263 [FIX] account_due_list_days_overdue version number
  account_due_list_days_overdue/__manifest__.py
Labels: approved

#261 [10.0] account_check_printing_report_base - refactor
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/views/report_check_base.xml
Labels: approved, needs review

#262 [10.0][add][account_payment_residual_amount]
  account_payment_residual_amount/README.rst
  account_payment_residual_amount/__init__.py
  account_payment_residual_amount/__manifest__.py
  account_payment_residual_amount/models/__init__.py
  account_payment_residual_amount/models/account_payment.py
  account_payment_residual_amount/readme/CONTRIBUTORS.rst
  account_payment_residual_amount/readme/DESCRIPTION.rst
  account_payment_residual_amount/static/description/icon.png
  account_payment_residual_amount/static/description/index.html
  account_payment_residual_amount/static/description/payments_view.png
  account_payment_residual_amount/tests/__init__.py
  account_payment_residual_amount/tests/test_account_payment_residual_amount.py
  account_payment_residual_amount/views/account_payment_view.xml
Labels: approved

#264 [10.0][FIX] greenify repo
  account_check_printing_report_base/report/check_print.py
Labels: approved

#267 [FIX]account_check_printing_report_base: Fix report printing Issue
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/views/report_check_base.xml
Labels: approved

#260 [11.0][MIG] partner_aging
  partner_aging/README.rst
  partner_aging/__init__.py
  partner_aging/__manifest__.py
  partner_aging/i18n/partner_aging.pot
  partner_aging/i18n/pt.po
  partner_aging/readme/CONTRIBUTORS.rst
  partner_aging/readme/DESCRIPTION.rst
  partner_aging/readme/USAGE.rst
  partner_aging/security/ir.model.access.csv
  partner_aging/static/description/icon.png
  partner_aging/static/description/index.html
  partner_aging/tests/__init__.py
  partner_aging/tests/test_partner_aging.py
  partner_aging/wizards/__init__.py
  partner_aging/wizards/res_partner_aging_customer.py
  partner_aging/wizards/res_partner_aging_customer.xml
  partner_aging/wizards/res_partner_aging_date.py
  partner_aging/wizards/res_partner_aging_supplier.py
  partner_aging/wizards/res_partner_aging_supplier.xml
Labels: needs review

#268 [12.0] [IMP] Payment Return Import ISO 20022: manage multiple notification, entry and details nodes
  account_payment_return_import_iso20022/__manifest__.py
  account_payment_return_import_iso20022/test_files/test-sepa-camt-unpaid-invalid.xml
  account_payment_return_import_iso20022/test_files/test-sepa-camt-unpaid.xml
  account_payment_return_import_iso20022/tests/test_import_iso20022.py
  account_payment_return_import_iso20022/wizard/camt_parser.py
Labels: approved

#257 [12.0][WIP]: Import payment return file with multiple xml documents
  account_payment_return_import_iso20022/wizard/payment_return_import.py
Labels: approved

#270 [12.0] [IMP] Payment Return: usability
  account_payment_return/models/payment_return.py
  account_payment_return/tests/test_payment_return.py
  account_payment_return/views/payment_return_view.xml
  account_payment_return_import/__manifest__.py
  account_payment_return_import/models/__init__.py
  account_payment_return_import/models/payment_return.py
  account_payment_return_import/models/payment_return_line.py
  account_payment_return_import/views/payment_return_view.xml
  account_payment_return_import/wizard/payment_return_import.py
Labels: approved, needs review, ready to merge
