Repository OCA/account-payment, pull requests merged in 2019-04, with the labels that each got.

#244 [10.0][FIX] account_payment_return: Constrains must raise ValidationE…
  account_payment_return/__manifest__.py
  account_payment_return/models/payment_return.py
  account_payment_return/tests/test_payment_return.py
Labels: approved

#242 [12.0][MIG] account_payment_show_invoice
  account_payment_show_invoice/README.rst
  account_payment_show_invoice/__init__.py
  account_payment_show_invoice/__manifest__.py
  account_payment_show_invoice/i18n/account_payment_show_invoice.pot
  account_payment_show_invoice/models/__init__.py
  account_payment_show_invoice/models/account_payment.py
  account_payment_show_invoice/readme/CONTRIBUTORS.rst
  account_payment_show_invoice/readme/DESCRIPTION.rst
  account_payment_show_invoice/readme/USAGE.rst
  account_payment_show_invoice/static/description/icon.png
  account_payment_show_invoice/static/description/index.html
  account_payment_show_invoice/tests/__init__.py
  account_payment_show_invoice/tests/test_payment_ref_invoice.py
  account_payment_show_invoice/views/account_payment_view.xml
Labels: approved, ready to merge

#239 [12.0][MIG] account_partner_reconcile
  account_partner_reconcile/README.rst
  account_partner_reconcile/__init__.py
  account_partner_reconcile/__manifest__.py
  account_partner_reconcile/i18n/account_partner_reconcile.pot
  account_partner_reconcile/models/__init__.py
  account_partner_reconcile/models/res_partner.py
  account_partner_reconcile/readme/CONFIGURE.rst
  account_partner_reconcile/readme/CONTRIBUTORS.rst
  account_partner_reconcile/readme/DESCRIPTION.rst
  account_partner_reconcile/static/description/icon.png
  account_partner_reconcile/tests/__init__.py
  account_partner_reconcile/tests/test_account_partner_reconcile.py
  account_partner_reconcile/views/res_partner_view.xml
Labels: approved, ready to merge

#234 [12.0] account_due_list: prevent to create or delete move lines, as not a use case for this module
  account_due_list/__manifest__.py
  account_due_list/views/payment_view.xml
Labels: approved, needs review
