Repository OCA/account-payment, pull requests merged in 2019-02, with the labels that each got.

#215 [12.0] [MIG] Account Payment Return Import
  account_payment_return_import/README.rst
  account_payment_return_import/__init__.py
  account_payment_return_import/__manifest__.py
  account_payment_return_import/i18n/account_payment_return_import.pot
  account_payment_return_import/i18n/am.po
  account_payment_return_import/i18n/ar.po
  account_payment_return_import/i18n/bg.po
  account_payment_return_import/i18n/ca.po
  account_payment_return_import/i18n/cs.po
  account_payment_return_import/i18n/de.po
  account_payment_return_import/i18n/el_GR.po
  account_payment_return_import/i18n/es.po
  account_payment_return_import/i18n/es_CR.po
  account_payment_return_import/i18n/es_EC.po
  account_payment_return_import/i18n/es_ES.po
  account_payment_return_import/i18n/es_MX.po
  account_payment_return_import/i18n/es_VE.po
  account_payment_return_import/i18n/et.po
  account_payment_return_import/i18n/fi.po
  account_payment_return_import/i18n/fr.po
  account_payment_return_import/i18n/gl.po
  account_payment_return_import/i18n/hr.po
  account_payment_return_import/i18n/hr_HR.po
  account_payment_return_import/i18n/it.po
  account_payment_return_import/i18n/lt.po
  account_payment_return_import/i18n/nl.po
  account_payment_return_import/i18n/nl_BE.po
  account_payment_return_import/i18n/pl.po
  account_payment_return_import/i18n/pt.po
  account_payment_return_import/i18n/pt_BR.po
  account_payment_return_import/i18n/pt_PT.po
  account_payment_return_import/i18n/ro.po
  account_payment_return_import/i18n/ru.po
  account_payment_return_import/i18n/sl.po
  account_payment_return_import/i18n/th.po
  account_payment_return_import/i18n/tr.po
  account_payment_return_import/i18n/vi.po
  account_payment_return_import/i18n/zh_CN.po
  account_payment_return_import/models/__init__.py
  account_payment_return_import/models/payment_return.py
  account_payment_return_import/readme/CONTRIBUTORS.rst
  account_payment_return_import/readme/DESCRIPTION.rst
  account_payment_return_import/readme/USAGE.rst
  account_payment_return_import/static/description/icon.png
  account_payment_return_import/static/description/index.html
  account_payment_return_import/test_files/test_empty.csv
  account_payment_return_import/test_files/test_payment_import.csv
  account_payment_return_import/test_files/test_payment_import.zip
  account_payment_return_import/test_files/test_zipped_payment_import_empty.zip
  account_payment_return_import/tests/__init__.py
  account_payment_return_import/tests/test_import_base.py
  account_payment_return_import/tests/test_import_file.py
  account_payment_return_import/tests/test_import_payment_return.py
  account_payment_return_import/wizard/__init__.py
  account_payment_return_import/wizard/base_parser.py
  account_payment_return_import/wizard/payment_return_import.py
  account_payment_return_import/wizard/payment_return_import_view.xml
  setup/account_payment_return_import/odoo/addons/account_payment_return_import
  setup/account_payment_return_import/setup.py
Labels: approved

#216 [12.0] [MIG] Account Payment Return Import SEPA PAIN
  account_payment_return_import_sepa_pain/README.rst
  account_payment_return_import_sepa_pain/__init__.py
  account_payment_return_import_sepa_pain/__manifest__.py
  account_payment_return_import_sepa_pain/data/unpaid_reason_codes.xml
  account_payment_return_import_sepa_pain/i18n/account_payment_return_import_sepa_pain.pot
  account_payment_return_import_sepa_pain/i18n/de.po
  account_payment_return_import_sepa_pain/i18n/es.po
  account_payment_return_import_sepa_pain/i18n/sl.po
  account_payment_return_import_sepa_pain/models/__init__.py
  account_payment_return_import_sepa_pain/models/payment_return.py
  account_payment_return_import_sepa_pain/readme/CONTRIBUTORS.rst
  account_payment_return_import_sepa_pain/readme/DESCRIPTION.rst
  account_payment_return_import_sepa_pain/readme/INSTALL.rst
  account_payment_return_import_sepa_pain/static/description/icon.png
  account_payment_return_import_sepa_pain/static/description/icon.svg
  account_payment_return_import_sepa_pain/static/description/index.html
  account_payment_return_import_sepa_pain/test_files/test-sepa-unpaid.xml
  account_payment_return_import_sepa_pain/test_files/test-sepa-unpaid.zip
  account_payment_return_import_sepa_pain/tests/__init__.py
  account_payment_return_import_sepa_pain/tests/test_import_sepa_pain.py
  account_payment_return_import_sepa_pain/wizard/__init__.py
  account_payment_return_import_sepa_pain/wizard/pain_parser.py
  account_payment_return_import_sepa_pain/wizard/payment_return_import.py
  oca_dependencies.txt
  setup/account_payment_return_import_sepa_pain/odoo/addons/account_payment_return_import_sepa_pain
  setup/account_payment_return_import_sepa_pain/setup.py
Labels: approved

#204 [10.0][IMP] account_payment_show_invoice: Add invoice on move line level
  account_payment_show_invoice/README.rst
  account_payment_show_invoice/__manifest__.py
  account_payment_show_invoice/models/__init__.py
  account_payment_show_invoice/models/account_move_line.py
  account_payment_show_invoice/views/account_move_line.xml
  account_payment_show_invoice/views/account_payment_view.xml
Labels: approved, ready to merge

#224 [IMP] account_check_printing: Allow to use other models
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/models/account_journal.py
  account_check_printing_report_base/report/check_print.py
Labels: approved

#228 [12.0] [ADD] Account Payment Return Import SEPA PAIN: missing return reasons
  account_payment_return/models/payment_return_reason.py
  account_payment_return_import_sepa_pain/__manifest__.py
  account_payment_return_import_sepa_pain/data/payment.return.reason.csv
  account_payment_return_import_sepa_pain/data/unpaid_reason_codes.xml
  account_payment_return_import_sepa_pain/i18n/account_payment_return_import_sepa_pain.pot
  account_payment_return_import_sepa_pain/i18n/de.po
  account_payment_return_import_sepa_pain/i18n/es.po
  account_payment_return_import_sepa_pain/i18n/sl.po
Labels: approved, needs review

#229 [12.0] [ADD] Payment Return Import SEPA: reason additional info
  account_payment_return/models/payment_return.py
  account_payment_return/views/payment_return_view.xml
  account_payment_return_import/tests/test_import_file.py
  account_payment_return_import_sepa_pain/test_files/test-sepa-unpaid.xml
  account_payment_return_import_sepa_pain/tests/test_import_sepa_pain.py
  account_payment_return_import_sepa_pain/wizard/pain_parser.py
Labels: approved
