Repository OCA/account-payment, pull requests merged in 2020-11, with the labels that each got.

#367 [13.0] [MIG] account_payment_promissory_note: Migration to v13
  account_payment_promissory_note/README.rst
  account_payment_promissory_note/__init__.py
  account_payment_promissory_note/__manifest__.py
  account_payment_promissory_note/i18n/account_payment_promissory_note.pot
  account_payment_promissory_note/i18n/es.po
  account_payment_promissory_note/models/__init__.py
  account_payment_promissory_note/models/account_abstract_payment.py
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/readme/CONTRIBUTORS.rst
  account_payment_promissory_note/readme/DESCRIPTION.rst
  account_payment_promissory_note/readme/USAGE.rst
  account_payment_promissory_note/static/description/icon.png
  account_payment_promissory_note/static/description/index.html
  account_payment_promissory_note/tests/__init__.py
  account_payment_promissory_note/tests/test_account_payment_promissory_note.py
  account_payment_promissory_note/views/account_payment_invoice_view.xml
  account_payment_promissory_note/views/account_payment_view.xml
  account_payment_promissory_note/wizard/__init__.py
  account_payment_promissory_note/wizard/account_register_payments.py
  setup/account_payment_promissory_note/odoo/addons/account_payment_promissory_note
  setup/account_payment_promissory_note/setup.py
Labels: approved, bot is merging ⏳

#368 [13.0] [IMP] account_check_printing_report_base: Add letter format to A4 checks
  account_check_printing_report_base/i18n/account_check_printing_report_base.pot
  account_check_printing_report_base/i18n/es.po
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/views/report_check_base.xml
Labels: approved, bot is merging ⏳, ready to merge

#376 FIX: use field supplier_rank instead of supplier
  account_payment_return/models/account_journal.py
Labels: bot is merging ⏳
