Repository OCA/account-payment, pull requests merged in 2020-03, with the labels that each got.

#308 [13.0][MIG] account_due_list_payment_mode
  account_due_list_payment_mode/README.rst
  account_due_list_payment_mode/__init__.py
  account_due_list_payment_mode/__manifest__.py
  account_due_list_payment_mode/i18n/account_due_list_payment_mode.pot
  account_due_list_payment_mode/i18n/de.po
  account_due_list_payment_mode/i18n/es.po
  account_due_list_payment_mode/readme/CONFIGURE.rst
  account_due_list_payment_mode/readme/CONTRIBUTORS.rst
  account_due_list_payment_mode/readme/DESCRIPTION.rst
  account_due_list_payment_mode/readme/INSTALL.rst
  account_due_list_payment_mode/readme/USAGE.rst
  account_due_list_payment_mode/static/description/icon.png
  account_due_list_payment_mode/static/description/index.html
  account_due_list_payment_mode/views/payment_view.xml
  oca_dependencies.txt
  setup/_metapackage/setup.py
  setup/account_due_list/setup.py
Labels: approved, ready to merge

#304 [13.0][MIG] account_payment_multi_deduction
  account_payment_multi_deduction/README.rst
  account_payment_multi_deduction/__init__.py
  account_payment_multi_deduction/__manifest__.py
  account_payment_multi_deduction/i18n/account_payment_multi_deduction.pot
  account_payment_multi_deduction/models/__init__.py
  account_payment_multi_deduction/models/account_payment.py
  account_payment_multi_deduction/readme/CONTRIBUTORS.rst
  account_payment_multi_deduction/readme/DESCRIPTION.rst
  account_payment_multi_deduction/readme/HISTORY.rst
  account_payment_multi_deduction/readme/INSTALL.rst
  account_payment_multi_deduction/readme/USAGE.rst
  account_payment_multi_deduction/security/ir.model.access.csv
  account_payment_multi_deduction/static/description/icon.png
  account_payment_multi_deduction/static/description/index.html
  account_payment_multi_deduction/tests/__init__.py
  account_payment_multi_deduction/tests/test_payment_multi_deduction.py
  account_payment_multi_deduction/views/account_payment_view.xml
Labels: approved

#315 [13.0][MIG] account_payment_return: Migration to 13.0
  account_payment_return/README.rst
  account_payment_return/__init__.py
  account_payment_return/__manifest__.py
  account_payment_return/data/ir_sequence_data.xml
  account_payment_return/i18n/account_payment_return.pot
  account_payment_return/i18n/am.po
  account_payment_return/i18n/ar.po
  account_payment_return/i18n/bg.po
  account_payment_return/i18n/ca.po
  account_payment_return/i18n/cs.po
  account_payment_return/i18n/de.po
  account_payment_return/i18n/el_GR.po
  account_payment_return/i18n/es.po
  account_payment_return/i18n/es_CR.po
  account_payment_return/i18n/es_EC.po
  account_payment_return/i18n/es_ES.po
  account_payment_return/i18n/es_MX.po
  account_payment_return/i18n/es_VE.po
  account_payment_return/i18n/et.po
  account_payment_return/i18n/fi.po
  account_payment_return/i18n/fr.po
  account_payment_return/i18n/gl.po
  account_payment_return/i18n/hr.po
  account_payment_return/i18n/hr_HR.po
  account_payment_return/i18n/it.po
  account_payment_return/i18n/lt.po
  account_payment_return/i18n/nl.po
  account_payment_return/i18n/nl_BE.po
  account_payment_return/i18n/pl.po
  account_payment_return/i18n/pt.po
  account_payment_return/i18n/pt_BR.po
  account_payment_return/i18n/pt_PT.po
  account_payment_return/i18n/ro.po
  account_payment_return/i18n/ru.po
  account_payment_return/i18n/sl.po
  account_payment_return/i18n/th.po
  account_payment_return/i18n/tr.po
  account_payment_return/i18n/vi.po
  account_payment_return/i18n/zh_CN.po
  account_payment_return/models/__init__.py
  account_payment_return/models/account_journal.py
  account_payment_return/models/account_move.py
  account_payment_return/models/payment_return.py
  account_payment_return/models/payment_return_reason.py
  account_payment_return/readme/CONTRIBUTORS.rst
  account_payment_return/readme/DESCRIPTION.rst
  account_payment_return/readme/USAGE.rst
  account_payment_return/security/account_payment_return_security.xml
  account_payment_return/security/ir.model.access.csv
  account_payment_return/static/description/icon.png
  account_payment_return/static/description/index.html
  account_payment_return/static/src/scss/account_payment_return.scss
  account_payment_return/static/src/xml/account_payment_return.xml
  account_payment_return/tests/__init__.py
  account_payment_return/tests/test_payment_return.py
  account_payment_return/views/account_journal_view.xml
  account_payment_return/views/account_move_views.xml
  account_payment_return/views/assets.xml
  account_payment_return/views/payment_return_view.xml
Labels: approved, ready to merge

#325 [13.0][MIG] account_payment_return_import: Migration to 13.0
  account_payment_return_import/README.rst
  account_payment_return_import/__init__.py
  account_payment_return_import/__manifest__.py
  account_payment_return_import/i18n/account_payment_return_import.pot
  account_payment_return_import/i18n/am.po
  account_payment_return_import/i18n/ar.po
  account_payment_return_import/i18n/bg.po
  account_payment_return_import/i18n/ca.po
  account_payment_return_import/i18n/cs.po
  account_payment_return_import/i18n/de.po
  account_payment_return_import/i18n/el_GR.po
  account_payment_return_import/i18n/es.po
  account_payment_return_import/i18n/es_CR.po
  account_payment_return_import/i18n/es_EC.po
  account_payment_return_import/i18n/es_ES.po
  account_payment_return_import/i18n/es_MX.po
  account_payment_return_import/i18n/es_VE.po
  account_payment_return_import/i18n/et.po
  account_payment_return_import/i18n/fi.po
  account_payment_return_import/i18n/fr.po
  account_payment_return_import/i18n/gl.po
  account_payment_return_import/i18n/hr.po
  account_payment_return_import/i18n/hr_HR.po
  account_payment_return_import/i18n/it.po
  account_payment_return_import/i18n/lt.po
  account_payment_return_import/i18n/nl.po
  account_payment_return_import/i18n/nl_BE.po
  account_payment_return_import/i18n/pl.po
  account_payment_return_import/i18n/pt.po
  account_payment_return_import/i18n/pt_BR.po
  account_payment_return_import/i18n/pt_PT.po
  account_payment_return_import/i18n/ro.po
  account_payment_return_import/i18n/ru.po
  account_payment_return_import/i18n/sl.po
  account_payment_return_import/i18n/th.po
  account_payment_return_import/i18n/tr.po
  account_payment_return_import/i18n/vi.po
  account_payment_return_import/i18n/zh_CN.po
  account_payment_return_import/models/__init__.py
  account_payment_return_import/models/payment_return.py
  account_payment_return_import/models/payment_return_line.py
  account_payment_return_import/readme/CONTRIBUTORS.rst
  account_payment_return_import/readme/DESCRIPTION.rst
  account_payment_return_import/readme/USAGE.rst
  account_payment_return_import/static/description/icon.png
  account_payment_return_import/static/description/index.html
  account_payment_return_import/test_files/test_empty.csv
  account_payment_return_import/test_files/test_payment_import.csv
  account_payment_return_import/test_files/test_payment_import.zip
  account_payment_return_import/test_files/test_zipped_payment_import_empty.zip
  account_payment_return_import/tests/__init__.py
  account_payment_return_import/tests/test_import_base.py
  account_payment_return_import/tests/test_import_file.py
  account_payment_return_import/tests/test_import_payment_return.py
  account_payment_return_import/views/payment_return_view.xml
  account_payment_return_import/wizard/__init__.py
  account_payment_return_import/wizard/base_parser.py
  account_payment_return_import/wizard/payment_return_import.py
  account_payment_return_import/wizard/payment_return_import_view.xml
Labels: approved, bot is merging ⏳
