Repository OCA/account-payment, pull requests merged in 2020-09, with the labels that each got.

#341 [FIX] account_cash_invoice : bad domain in xml view generate error in many journals context
  account_cash_invoice/wizard/cash_invoice_in.xml
  account_cash_invoice/wizard/cash_invoice_out.xml
Labels: approved, bot is merging ⏳, ready to merge

#338 [12.0][ADD] - Add action menu for payment return reasons
  account_payment_return/__manifest__.py
  account_payment_return/views/payment_return_reason.xml
Labels: approved, bot is merging ⏳, ready to merge

#335 [13.0][ADD] account_check_date
  account_check_date/README.rst
  account_check_date/__init__.py
  account_check_date/__manifest__.py
  account_check_date/models/__init__.py
  account_check_date/models/account_payment.py
  account_check_date/readme/CONTRIBUTORS.rst
  account_check_date/readme/DESCRIPTION.rst
  account_check_date/readme/USAGE.rst
  account_check_date/static/description/icon.png
  account_check_date/static/description/index.html
  account_check_date/views/account_payment_views.xml
  setup/account_check_date/odoo/addons/account_check_date
  setup/account_check_date/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#346 [13.0] [MIG] account_payment_return_import_iso20022: Migration to v13
  account_payment_return_import_iso20022/README.rst
  account_payment_return_import_iso20022/__init__.py
  account_payment_return_import_iso20022/__manifest__.py
  account_payment_return_import_iso20022/data/payment.return.reason.csv
  account_payment_return_import_iso20022/i18n/account_payment_return_import_iso20022.pot
  account_payment_return_import_iso20022/i18n/es.po
  account_payment_return_import_iso20022/models/__init__.py
  account_payment_return_import_iso20022/models/payment_return.py
  account_payment_return_import_iso20022/readme/CONTRIBUTORS.rst
  account_payment_return_import_iso20022/readme/DESCRIPTION.rst
  account_payment_return_import_iso20022/readme/INSTALL.rst
  account_payment_return_import_iso20022/static/description/icon.png
  account_payment_return_import_iso20022/static/description/index.html
  account_payment_return_import_iso20022/test_files/test-sepa-camt-unpaid-invalid.xml
  account_payment_return_import_iso20022/test_files/test-sepa-camt-unpaid.xml
  account_payment_return_import_iso20022/test_files/test-sepa-camt-unpaid.zip
  account_payment_return_import_iso20022/test_files/test-sepa-pain-unpaid-invalid.xml
  account_payment_return_import_iso20022/test_files/test-sepa-pain-unpaid.xml
  account_payment_return_import_iso20022/test_files/test-sepa-pain-unpaid.zip
  account_payment_return_import_iso20022/tests/__init__.py
  account_payment_return_import_iso20022/tests/test_import_iso20022.py
  account_payment_return_import_iso20022/wizard/__init__.py
  account_payment_return_import_iso20022/wizard/camt_parser.py
  account_payment_return_import_iso20022/wizard/pain_parser.py
  account_payment_return_import_iso20022/wizard/payment_return_import.py
  partner_aging/wizard/res_partner_aging_customer.py
  partner_aging/wizard/res_partner_aging_supplier.py
  setup/account_payment_return_import_iso20022/odoo/addons/account_payment_return_import_iso20022
  setup/account_payment_return_import_iso20022/setup.py
Labels: approved, bot is merging ⏳

#353 [FIX] account_payment_multi_deduction: Add groups_id in view
  account_payment_multi_deduction/__manifest__.py
  account_payment_multi_deduction/views/account_payment_view.xml
Labels: bot is merging ⏳

#354 [12.0] [IMP] account_check_printing_report_base: Added a template to print checks in a4 documents
  account_check_printing_report_base/README.rst
  account_check_printing_report_base/data/account_payment_check_report_data.xml
  account_check_printing_report_base/data/report_paperformat_parameter.xml
  account_check_printing_report_base/i18n/account_check_printing_report_base.pot
  account_check_printing_report_base/i18n/es.po
  account_check_printing_report_base/readme/CONTRIBUTORS.rst
  account_check_printing_report_base/readme/INSTALL.rst
  account_check_printing_report_base/report/account_check_writing_report.xml
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/static/description/index.html
  account_check_printing_report_base/views/report_check_base.xml
Labels: approved, bot is merging ⏳, ready to merge

#356 [13.0][UPD] Eficent -> ForgeFlow
  account_due_list_days_overdue/README.rst
  account_due_list_days_overdue/__init__.py
  account_due_list_days_overdue/__manifest__.py
  account_due_list_days_overdue/demo/account_overdue_term_demo.xml
  account_due_list_days_overdue/models/__init__.py
  account_due_list_days_overdue/models/account_move_line.py
  account_due_list_days_overdue/models/account_overdue_term.py
  account_due_list_days_overdue/readme/CONTRIBUTORS.rst
  account_due_list_days_overdue/static/description/index.html
  account_due_list_days_overdue/tests/__init__.py
  account_due_list_days_overdue/tests/test_account_due_list_days_overdue.py
Labels: approved, bot is merging ⏳
