Repository OCA/account-payment, pull requests merged in 2020-10, with the labels that each got.

#357 [13.0][IMP] account_payment_multi_deduction, add hook when create deduction move line
  account_payment_multi_deduction/models/account_payment.py
Labels: bot is merging ⏳

#350 [ADD] sale_payment_mgmt: New module
  sale_payment_mgmt/__init__.py
  sale_payment_mgmt/__manifest__.py
  sale_payment_mgmt/i18n/es.po
  sale_payment_mgmt/i18n/sale_payment_mgmt.pot
  sale_payment_mgmt/models/__init__.py
  sale_payment_mgmt/models/account_payment.py
  sale_payment_mgmt/readme/CONTRIBUTORS.rst
  sale_payment_mgmt/readme/DESCRIPTION.rst
  sale_payment_mgmt/readme/USAGE
  sale_payment_mgmt/security/ir.model.access.csv
  sale_payment_mgmt/security/security.xml
  sale_payment_mgmt/static/description/icon.png
  sale_payment_mgmt/static/description/payment_menu.png
  sale_payment_mgmt/tests/__init__.py
  sale_payment_mgmt/tests/test_access_rights.py
  sale_payment_mgmt/views/account_move_view.xml
  sale_payment_mgmt/views/account_payment_view.xml
  setup/sale_payment_mgmt/odoo/addons/sale_payment_mgmt
  setup/sale_payment_mgmt/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#359 [13.0][IMP] account_payment_multi_deduction, ability to multi deduct with keep open
  account_payment_multi_deduction/models/account_payment.py
  account_payment_multi_deduction/tests/test_payment_multi_deduction.py
  account_payment_multi_deduction/views/account_payment_view.xml
Labels: bot is merging ⏳

#351 [13.0] [MIG] account_check_printing_report_base: Migration to v13.0
  account_check_printing_report_base/README.rst
  account_check_printing_report_base/__init__.py
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/data/account_payment_check_report_data.xml
  account_check_printing_report_base/data/report_paperformat.xml
  account_check_printing_report_base/i18n/account_check_printing_report_base.pot
  account_check_printing_report_base/i18n/es.po
  account_check_printing_report_base/i18n/pt.po
  account_check_printing_report_base/models/__init__.py
  account_check_printing_report_base/models/account_journal.py
  account_check_printing_report_base/models/account_payment.py
  account_check_printing_report_base/models/account_payment_check_report.py
  account_check_printing_report_base/models/res_company.py
  account_check_printing_report_base/readme/CONFIGURE.rst
  account_check_printing_report_base/readme/CONTRIBUTORS.rst
  account_check_printing_report_base/readme/DESCRIPTION.rst
  account_check_printing_report_base/readme/ROADMAP.rst
  account_check_printing_report_base/readme/USAGE.rst
  account_check_printing_report_base/report/__init__.py
  account_check_printing_report_base/report/account_check_writing_report.xml
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/security/ir.model.access.csv
  account_check_printing_report_base/static/description/icon.png
  account_check_printing_report_base/static/description/index.html
  account_check_printing_report_base/tests/__init__.py
  account_check_printing_report_base/tests/test_check_printing_report.py
  account_check_printing_report_base/views/account_journal_view.xml
  account_check_printing_report_base/views/account_payment_check_report_view.xml
  account_check_printing_report_base/views/report_check_base.xml
  account_check_printing_report_base/views/res_company_view.xml
  oca_dependencies.txt
  setup/account_check_printing_report_base/odoo/addons/account_check_printing_report_base
  setup/account_check_printing_report_base/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#352 [12.0] [ADD] account_payment_promissory_note: Module that adds a due date on payments
  account_payment_promissory_note/README.rst
  account_payment_promissory_note/__init__.py
  account_payment_promissory_note/__manifest__.py
  account_payment_promissory_note/i18n/account_payment_promissory_note.pot
  account_payment_promissory_note/i18n/es.po
  account_payment_promissory_note/models/__init__.py
  account_payment_promissory_note/models/account_abstract_payment.py
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/readme/CONTRIBUTORS.rst
  account_payment_promissory_note/readme/DESCRIPTION.rst
  account_payment_promissory_note/readme/USAGE.rst
  account_payment_promissory_note/static/description/icon.png
  account_payment_promissory_note/static/description/index.html
  account_payment_promissory_note/tests/__init__.py
  account_payment_promissory_note/tests/test_account_payment_promissory_note.py
  account_payment_promissory_note/views/account_payment_invoice_view.xml
  account_payment_promissory_note/views/account_payment_view.xml
  account_payment_promissory_note/wizard/__init__.py
  account_payment_promissory_note/wizard/account_register_payments.py
Labels: approved, bot is merging ⏳

#362 [12.0] [FIX+IMP] account_payment_promissory_note: Fixed a bug with invoce multi payment and add code to allow print promisory notes
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/data/report_paperformat.xml
  account_check_printing_report_base/report/__init__.py
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/report/lang.py
  account_check_printing_report_base/views/account_journal_view.xml
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/wizard/account_register_payments.py
Labels: approved, bot is merging ⏳

#366 [13.0] [IMP] account_check_printing_report_base: Added IMP set on v12
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/data/report_paperformat.xml
  account_check_printing_report_base/report/__init__.py
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/report/lang.py
  account_check_printing_report_base/tests/__init__.py
  account_check_printing_report_base/tests/test_check_printing_report.py
  account_check_printing_report_base/tests/test_num2words_lang_solution.py
Labels: approved, bot is merging ⏳
