Repository OCA/account-payment, pull requests merged in 2021-11, with the labels that each got.

#460 [14.0][FIX] account_payment_multI_deduction - not overwrite context on register payment multi
  account_payment_multi_deduction/wizard/account_payment_register.py
Labels: bot is merging ⏳

#398 [14.0][ADD] account_payment_batch_process_discount
  account_payment_batch_process_discount/README.rst
  account_payment_batch_process_discount/__init__.py
  account_payment_batch_process_discount/__manifest__.py
  account_payment_batch_process_discount/models/__init__.py
  account_payment_batch_process_discount/models/account_move.py
  account_payment_batch_process_discount/models/account_payment_term_line.py
  account_payment_batch_process_discount/readme/CONFIGURE.rst
  account_payment_batch_process_discount/readme/CONTRIBUTORS.rst
  account_payment_batch_process_discount/readme/DESCRIPTION.rst
  account_payment_batch_process_discount/readme/USAGE.rst
  account_payment_batch_process_discount/static/description/icon.png
  account_payment_batch_process_discount/views/account_move.xml
  account_payment_batch_process_discount/wizard/__init__.py
  account_payment_batch_process_discount/wizard/account_payment_register.py
  account_payment_batch_process_discount/wizard/invoice_payment_line.py
  setup/account_payment_batch_process_discount/odoo/addons/account_payment_batch_process_discount
  setup/account_payment_batch_process_discount/setup.py
Labels: enhancement, needs review, bot is merging ⏳

#405 [14.0][MIG]Migrated account_payment_credit_card
  account_payment_credit_card/README.rst
  account_payment_credit_card/__init__.py
  account_payment_credit_card/__manifest__.py
  account_payment_credit_card/i18n/account_payment_credit_card.pot
  account_payment_credit_card/models/__init__.py
  account_payment_credit_card/models/account.py
  account_payment_credit_card/models/account_move.py
  account_payment_credit_card/readme/CONFIGURE.rst
  account_payment_credit_card/readme/CONTRIBUTORS.rst
  account_payment_credit_card/readme/DESCRIPTION.rst
  account_payment_credit_card/readme/USAGE.rst
  account_payment_credit_card/static/description/icon.png
  account_payment_credit_card/static/description/index.html
  account_payment_credit_card/tests/__init__.py
  account_payment_credit_card/tests/test_payment_credit_card.py
  account_payment_credit_card/views/account_view.xml
  setup/account_payment_credit_card/odoo/addons/account_payment_credit_card
  setup/account_payment_credit_card/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#461 [14.0][MIG] account_cash_invoice from 13.0 to 14.0
  account_cash_invoice/README.rst
  account_cash_invoice/__init__.py
  account_cash_invoice/__manifest__.py
  account_cash_invoice/i18n/account_cash_invoice.pot
  account_cash_invoice/i18n/hr.po
  account_cash_invoice/i18n/pt.po
  account_cash_invoice/models/__init__.py
  account_cash_invoice/models/account_bank_statement_line.py
  account_cash_invoice/readme/CONTRIBUTORS.rst
  account_cash_invoice/readme/DESCRIPTION.rst
  account_cash_invoice/readme/ROADMAP.rst
  account_cash_invoice/readme/USAGE.rst
  account_cash_invoice/security/ir.model.access.csv
  account_cash_invoice/static/description/icon.png
  account_cash_invoice/static/description/index.html
  account_cash_invoice/tests/__init__.py
  account_cash_invoice/tests/test_pay_invoice.py
  account_cash_invoice/wizard/__init__.py
  account_cash_invoice/wizard/cash_invoice_in.py
  account_cash_invoice/wizard/cash_invoice_in.xml
  account_cash_invoice/wizard/cash_invoice_out.py
  account_cash_invoice/wizard/cash_invoice_out.xml
  setup/account_cash_invoice/odoo/addons/account_cash_invoice
  setup/account_cash_invoice/setup.py
Labels: approved, ready to merge, bot is merging ⏳
