Repository OCA/account-payment, pull requests merged in 2021-03, with the labels that each got.

#361 [13.0][FIX] register payment with multi invoice - Expected singleton
  account_payment_multi_deduction/models/account_payment.py
Labels: approved, bot is merging ⏳, ready to merge

#399 [13.0][FIX] account_payment_return_import + partner_aging: Set correct journal in tests to prevent error
  account_payment_return_import/tests/test_import_base.py
  partner_aging/tests/test_partner_aging.py
Labels: approved, bot is merging ⏳

#372 [13.0][IMP] account_payment_promissory_note: Changes on due_date
  account_payment_promissory_note/i18n/account_payment_promissory_note.pot
  account_payment_promissory_note/i18n/es.po
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/views/account_payment_invoice_view.xml
  account_payment_promissory_note/wizard/account_register_payments.py
Labels: approved, bot is merging ⏳

#390 [ADD][14.0] account_payment_term_discount
  account_payment_term_discount/README.rst
  account_payment_term_discount/__init__.py
  account_payment_term_discount/__manifest__.py
  account_payment_term_discount/changes.txt
  account_payment_term_discount/i18n/account_cash_discount_61.pot
  account_payment_term_discount/i18n/de.po
  account_payment_term_discount/models/__init__.py
  account_payment_term_discount/models/account_move.py
  account_payment_term_discount/models/account_payment.py
  account_payment_term_discount/models/account_payment_term.py
  account_payment_term_discount/models/product.py
  account_payment_term_discount/readme/CONFIGURE.rst
  account_payment_term_discount/readme/CONTRIBUTORS.rst
  account_payment_term_discount/readme/CREDITS.rst
  account_payment_term_discount/readme/DESCRIPTION.rst
  account_payment_term_discount/readme/USAGE.rst
  account_payment_term_discount/security/ir.model.access.csv
  account_payment_term_discount/static/description/icon.png
  account_payment_term_discount/tests/__init__.py
  account_payment_term_discount/tests/test_customer_payment_term.py
  account_payment_term_discount/views/account_move_view.xml
  account_payment_term_discount/views/account_payment_term_view.xml
  account_payment_term_discount/views/account_payment_view.xml
  account_payment_term_discount/views/product_view.xml
  account_payment_term_extension/__manifest__.py
  setup/account_payment_term_discount/odoo/addons/account_payment_term_discount
  setup/account_payment_term_discount/setup.py
Labels: bot is merging ⏳, enhancement, needs fixing, needs review

#348 Adding path to activate Full Accounting Settings
  account_due_list/readme/CONFIGURE.rst
Labels: approved, bot is merging ⏳, ready to merge
