Repository OCA/account-payment, pull requests merged in 2021-07, with the labels that each got.

#421 [12.0][ADD] account_payment_term_partner_holiday: Add partner holidays to exclude it when payment term assigned in invoices set due dates
  account_payment_term_partner_holiday/README.rst
  account_payment_term_partner_holiday/__init__.py
  account_payment_term_partner_holiday/__manifest__.py
  account_payment_term_partner_holiday/i18n/account_payment_term_partner_holiday.pot
  account_payment_term_partner_holiday/i18n/es.po
  account_payment_term_partner_holiday/models/__init__.py
  account_payment_term_partner_holiday/models/account_invoice.py
  account_payment_term_partner_holiday/models/account_payment_term.py
  account_payment_term_partner_holiday/models/res_partner.py
  account_payment_term_partner_holiday/readme/CONTRIBUTORS.rst
  account_payment_term_partner_holiday/readme/DESCRIPTION.rst
  account_payment_term_partner_holiday/readme/USAGE.rst
  account_payment_term_partner_holiday/security/ir.model.access.csv
  account_payment_term_partner_holiday/static/description/icon.png
  account_payment_term_partner_holiday/static/description/index.html
  account_payment_term_partner_holiday/tests/__init__.py
  account_payment_term_partner_holiday/tests/test_partner_holiday.py
  account_payment_term_partner_holiday/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#403 [14.0] [account_payment_term_extension] [FIX] error computing months …
  account_payment_term_extension/models/account_payment_term.py
  account_payment_term_extension/tests/test_payment_term.py
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#391 [14.0][ADD] account_payment_batch_process
  account_payment_batch_process/README.rst
  account_payment_batch_process/__init__.py
  account_payment_batch_process/__manifest__.py
  account_payment_batch_process/models/__init__.py
  account_payment_batch_process/models/payment_adjustment_reason.py
  account_payment_batch_process/readme/CONTRIBUTORS.rst
  account_payment_batch_process/readme/CREDITS.rst
  account_payment_batch_process/readme/DESCRIPTION.rst
  account_payment_batch_process/readme/HISTORY.rst
  account_payment_batch_process/security/ir.model.access.csv
  account_payment_batch_process/static/description/icon.png
  account_payment_batch_process/views/account_move.xml
  account_payment_batch_process/views/account_payment.xml
  account_payment_batch_process/wizard/__init__.py
  account_payment_batch_process/wizard/account_payment_register.py
  account_payment_batch_process/wizard/account_payment_register.xml
  account_payment_batch_process/wizard/invoice_payment_line.py
  requirements.txt
  setup/account_payment_batch_process/odoo/addons/account_payment_batch_process
  setup/account_payment_batch_process/setup.py
Labels: approved, bot is merging ⏳, needs fixing, work in progress

#409 [13.0][FIX] account_check_printing_report_base: mistypo in args
  account_check_printing_report_base/report/lang.py
  requirements.txt
Labels: approved, bot is merging ⏳

#423 [14.0][FIX] account_payment_term_discount typo
  account_payment_term_discount/models/product.py
Labels: approved, bot is merging ⏳, ready to merge

#424 [14.0][ADD] account_payment_view_check_number
  account_payment_view_check_number/README.rst
  account_payment_view_check_number/__init__.py
  account_payment_view_check_number/__manifest__.py
  account_payment_view_check_number/readme/CONFIGURE.rst
  account_payment_view_check_number/readme/CONTRIBUTORS.rst
  account_payment_view_check_number/readme/DESCRIPTION.rst
  account_payment_view_check_number/readme/USAGE.rst
  account_payment_view_check_number/static/description/index.html
  account_payment_view_check_number/views/account_payment_view.xml
  setup/account_payment_view_check_number/odoo/addons/account_payment_view_check_number
  setup/account_payment_view_check_number/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#425 [13.0][MIG] account_payment_term_partner_holiday: Migration to 13.0
  account_payment_term_partner_holiday/README.rst
  account_payment_term_partner_holiday/__init__.py
  account_payment_term_partner_holiday/__manifest__.py
  account_payment_term_partner_holiday/i18n/account_payment_term_partner_holiday.pot
  account_payment_term_partner_holiday/i18n/es.po
  account_payment_term_partner_holiday/models/__init__.py
  account_payment_term_partner_holiday/models/account_move.py
  account_payment_term_partner_holiday/models/account_payment_term.py
  account_payment_term_partner_holiday/models/res_partner.py
  account_payment_term_partner_holiday/readme/CONTRIBUTORS.rst
  account_payment_term_partner_holiday/readme/DESCRIPTION.rst
  account_payment_term_partner_holiday/readme/USAGE.rst
  account_payment_term_partner_holiday/security/ir.model.access.csv
  account_payment_term_partner_holiday/static/description/icon.png
  account_payment_term_partner_holiday/static/description/index.html
  account_payment_term_partner_holiday/tests/__init__.py
  account_payment_term_partner_holiday/tests/test_partner_holiday.py
  account_payment_term_partner_holiday/views/res_partner_view.xml
  setup/account_payment_term_partner_holiday/odoo/addons/account_payment_term_partner_holiday
  setup/account_payment_term_partner_holiday/setup.py
Labels: bot is merging ⏳

#427 [13.0][FIX] account_check_printing_report_base: Pin num2words version and fix typo in function call
  account_check_printing_report_base/report/lang.py
  requirements.txt
Labels: approved, bot is merging ⏳

#429 [12.0][FIX] account_payment_term_partner_holiday: Improve is_date_in_holiday() to filtered correctly when day_to is less than date to compare
  account_payment_term_partner_holiday/README.rst
  account_payment_term_partner_holiday/__manifest__.py
  account_payment_term_partner_holiday/migrations/12.0.1.1.0/post-migration.py
  account_payment_term_partner_holiday/models/account_invoice.py
  account_payment_term_partner_holiday/models/account_payment_term.py
  account_payment_term_partner_holiday/models/res_partner.py
  account_payment_term_partner_holiday/readme/ROADMAP.rst
  account_payment_term_partner_holiday/static/description/index.html
  account_payment_term_partner_holiday/tests/test_partner_holiday.py
  account_payment_term_partner_holiday/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#408 [14.0][MIG] Migrated a partner_aging module.
  partner_aging/README.rst
  partner_aging/__init__.py
  partner_aging/__manifest__.py
  partner_aging/i18n/partner_aging.pot
  partner_aging/i18n/pt.po
  partner_aging/readme/CONTRIBUTORS.rst
  partner_aging/readme/CREDITS.rst
  partner_aging/readme/DESCRIPTION.rst
  partner_aging/readme/USAGE.rst
  partner_aging/security/ir.model.access.csv
  partner_aging/static/description/icon.png
  partner_aging/static/description/index.html
  partner_aging/tests/__init__.py
  partner_aging/tests/test_partner_aging.py
  partner_aging/wizard/__init__.py
  partner_aging/wizard/res_partner_aging_customer.py
  partner_aging/wizard/res_partner_aging_customer.xml
  partner_aging/wizard/res_partner_aging_date.py
  partner_aging/wizard/res_partner_aging_supplier.py
  partner_aging/wizard/res_partner_aging_supplier.xml
  setup/partner_aging/odoo/addons/partner_aging
  setup/partner_aging/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#374 [14.0][MIG] account_payment_multi_deduction
  account_payment_multi_deduction/README.rst
  account_payment_multi_deduction/__init__.py
  account_payment_multi_deduction/__manifest__.py
  account_payment_multi_deduction/i18n/account_payment_multi_deduction.pot
  account_payment_multi_deduction/models/__init__.py
  account_payment_multi_deduction/models/account_payment.py
  account_payment_multi_deduction/readme/CONTRIBUTORS.rst
  account_payment_multi_deduction/readme/DESCRIPTION.rst
  account_payment_multi_deduction/readme/HISTORY.rst
  account_payment_multi_deduction/readme/USAGE.rst
  account_payment_multi_deduction/security/ir.model.access.csv
  account_payment_multi_deduction/static/description/icon.png
  account_payment_multi_deduction/static/description/index.html
  account_payment_multi_deduction/tests/__init__.py
  account_payment_multi_deduction/tests/test_payment_multi_deduction.py
  account_payment_multi_deduction/wizard/__init__.py
  account_payment_multi_deduction/wizard/account_payment_deduction.py
  account_payment_multi_deduction/wizard/account_payment_register.py
  account_payment_multi_deduction/wizard/account_payment_register_views.xml
  setup/account_payment_multi_deduction/odoo/addons/account_payment_multi_deduction
  setup/account_payment_multi_deduction/setup.py
Labels: bot is merging ⏳

#231 [12.0][MIG] account_early_payment_discount
  account_early_payment_discount/README.rst
  account_early_payment_discount/__init__.py
  account_early_payment_discount/__manifest__.py
  account_early_payment_discount/docs/payment_term_form.png
  account_early_payment_discount/i18n/account_early_payment_discount.pot
  account_early_payment_discount/models/__init__.py
  account_early_payment_discount/models/account_payment_term.py
  account_early_payment_discount/readme/CONFIGURE.rst
  account_early_payment_discount/readme/CONTRIBUTORS.rst
  account_early_payment_discount/readme/DESCRIPTION.rst
  account_early_payment_discount/static/description/index.html
  account_early_payment_discount/tests/__init__.py
  account_early_payment_discount/tests/test_payment_term.py
  account_early_payment_discount/views/account_payment_term.xml
Labels: bot is merging ⏳

#430 [13.0][FIX] account_payment_term_partner_holiday: Improve is_date_in_holiday() to filtered correctly when day_to is less than date to compare
  account_payment_term_partner_holiday/README.rst
  account_payment_term_partner_holiday/__manifest__.py
  account_payment_term_partner_holiday/migrations/13.0.1.1.0/post-migration.py
  account_payment_term_partner_holiday/models/account_move.py
  account_payment_term_partner_holiday/models/account_payment_term.py
  account_payment_term_partner_holiday/models/res_partner.py
  account_payment_term_partner_holiday/readme/ROADMAP.rst
  account_payment_term_partner_holiday/static/description/index.html
  account_payment_term_partner_holiday/tests/test_partner_holiday.py
  account_payment_term_partner_holiday/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#433 [FIX] account_payment_term_discount: payment_state in tests
  account_payment_term_discount/models/account_payment.py
  account_payment_term_discount/tests/test_customer_payment_term.py
Labels: approved, bot is merging ⏳, bug, needs review

#436 [FIX] account_payment_term_discount
  account_payment_term_discount/wizard/account_payment_register.py
Labels: bot is merging ⏳, bug, needs review
