Repository OCA/account-payment, pull requests merged in 2022-04, with the labels that each got.

#498 [15.0][MIG] account_due_list: Migration to 15.0
  account_due_list/README.rst
  account_due_list/__init__.py
  account_due_list/__manifest__.py
  account_due_list/i18n/account_due_list.pot
  account_due_list/i18n/bg.po
  account_due_list/i18n/da.po
  account_due_list/i18n/de.po
  account_due_list/i18n/el_GR.po
  account_due_list/i18n/es.po
  account_due_list/i18n/es_AR.po
  account_due_list/i18n/es_MX.po
  account_due_list/i18n/fi.po
  account_due_list/i18n/fr.po
  account_due_list/i18n/fr_CH.po
  account_due_list/i18n/fr_FR.po
  account_due_list/i18n/hr.po
  account_due_list/i18n/it.po
  account_due_list/i18n/nb.po
  account_due_list/i18n/nl.po
  account_due_list/i18n/pt.po
  account_due_list/i18n/pt_BR.po
  account_due_list/i18n/pt_PT.po
  account_due_list/i18n/sk.po
  account_due_list/i18n/sl.po
  account_due_list/i18n/tr.po
  account_due_list/i18n/zh_CN.po
  account_due_list/init_hook.py
  account_due_list/models/__init__.py
  account_due_list/models/account_move_line.py
  account_due_list/readme/CONFIGURE.rst
  account_due_list/readme/CONTRIBUTORS.rst
  account_due_list/readme/DESCRIPTION.rst
  account_due_list/readme/USAGE.rst
  account_due_list/static/description/icon.png
  account_due_list/static/description/index.html
  account_due_list/views/payment_view.xml
  setup/account_due_list/odoo/addons/account_due_list
  setup/account_due_list/setup.py
Labels: approved, bot is merging ⏳

#493 [15.0][MIG] account_payment_widget_amount
  account_payment_widget_amount/README.rst
  account_payment_widget_amount/__init__.py
  account_payment_widget_amount/__manifest__.py
  account_payment_widget_amount/i18n/account_payment_widget_amount.pot
  account_payment_widget_amount/i18n/pt.po
  account_payment_widget_amount/i18n/pt_BR.po
  account_payment_widget_amount/models/__init__.py
  account_payment_widget_amount/models/account_move_line.py
  account_payment_widget_amount/readme/CONTRIBUTORS.rst
  account_payment_widget_amount/readme/DESCRIPTION.rst
  account_payment_widget_amount/readme/USAGE.rst
  account_payment_widget_amount/static/description/icon.png
  account_payment_widget_amount/static/description/index.html
  account_payment_widget_amount/static/description/payment_widget.png
  account_payment_widget_amount/static/description/payment_widget_amount_reconciled.png
  account_payment_widget_amount/static/src/js/account_payment_field.js
  account_payment_widget_amount/static/src/xml/account_payment.xml
  account_payment_widget_amount/tests/__init__.py
  account_payment_widget_amount/tests/test_account_payment_widget_amount.py
  setup/account_payment_widget_amount/odoo/addons/account_payment_widget_amount
  setup/account_payment_widget_amount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#501 [FIX] account_due_list: Do not require administrator rights
  account_due_list/models/account_move_line.py
Labels: bot is merging ⏳
