Repository OCA/account-payment, pull requests merged in 2022-11, with the labels that each got.

#554 [FIX] pre-commit py-lint error
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#521 [15.0][MIG] account_payment_promissory_note: Migration to 15.0
  account_payment_promissory_note/README.rst
  account_payment_promissory_note/__init__.py
  account_payment_promissory_note/__manifest__.py
  account_payment_promissory_note/i18n/account_payment_promissory_note.pot
  account_payment_promissory_note/i18n/es.po
  account_payment_promissory_note/models/__init__.py
  account_payment_promissory_note/models/account_abstract_payment.py
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/readme/CONTRIBUTORS.rst
  account_payment_promissory_note/readme/DESCRIPTION.rst
  account_payment_promissory_note/readme/USAGE.rst
  account_payment_promissory_note/static/description/icon.png
  account_payment_promissory_note/static/description/index.html
  account_payment_promissory_note/tests/__init__.py
  account_payment_promissory_note/tests/test_account_payment_promissory_note.py
  account_payment_promissory_note/views/account_payment_invoice_view.xml
  account_payment_promissory_note/views/account_payment_view.xml
  account_payment_promissory_note/wizard/__init__.py
  account_payment_promissory_note/wizard/account_register_payments.py
  setup/account_payment_promissory_note/odoo/addons/account_payment_promissory_note
  setup/account_payment_promissory_note/setup.py
Labels: approved, bot is merging ⏳

#552 [15.0][MIG] partner_aging
  partner_aging/README.rst
  partner_aging/__init__.py
  partner_aging/__manifest__.py
  partner_aging/i18n/fr.po
  partner_aging/i18n/partner_aging.pot
  partner_aging/i18n/pt.po
  partner_aging/readme/CONTRIBUTORS.rst
  partner_aging/readme/CREDITS.rst
  partner_aging/readme/DESCRIPTION.rst
  partner_aging/readme/USAGE.rst
  partner_aging/security/ir.model.access.csv
  partner_aging/static/description/icon.png
  partner_aging/static/description/index.html
  partner_aging/tests/__init__.py
  partner_aging/tests/test_partner_aging.py
  partner_aging/wizard/__init__.py
  partner_aging/wizard/res_partner_aging_customer.py
  partner_aging/wizard/res_partner_aging_customer.xml
  partner_aging/wizard/res_partner_aging_date.py
  partner_aging/wizard/res_partner_aging_supplier.py
  partner_aging/wizard/res_partner_aging_supplier.xml
  setup/partner_aging/odoo/addons/partner_aging
  setup/partner_aging/setup.py
Labels: needs review, migration, bot is merging ⏳

#553 [14.0][FIX] partner_aging: Customer and supplier aging query
  .github/workflows/pre-commit.yml
  partner_aging/wizard/res_partner_aging_customer.py
  partner_aging/wizard/res_partner_aging_supplier.py
Labels: bug, needs review, bot is merging ⏳

#557 [IMP] account_payment_notification: display envelope
  .copier-answers.yml
  .pre-commit-config.yaml
  account_payment_notification/models/account_payment.py
  account_payment_notification/tests/test_notifications.py
Labels: approved, ready to merge, bot is merging ⏳

#551 [12.0][FIX] partner_aging: Fixed customer and supplier aging query
  partner_aging/wizard/res_partner_aging_customer.py
  partner_aging/wizard/res_partner_aging_supplier.py
Labels: bug, needs review
