Repository OCA/account-payment, pull requests merged in 2022-10, with the labels that each got.

#543 [UPD] add index on invoice_id to speed up performance on big databases
  account_cash_invoice/models/account_bank_statement_line.py
Labels: approved, ready to merge, bot is merging ⏳

#464 [14.0][MIG] account_financial_discount
  account_financial_discount/README.rst
  account_financial_discount/__init__.py
  account_financial_discount/__manifest__.py
  account_financial_discount/models/__init__.py
  account_financial_discount/models/account_move.py
  account_financial_discount/models/account_move_line.py
  account_financial_discount/models/account_payment_term.py
  account_financial_discount/models/account_reconcile_model.py
  account_financial_discount/models/res_company.py
  account_financial_discount/models/res_config_settings.py
  account_financial_discount/readme/CONFIGURE.rst
  account_financial_discount/readme/CONTRIBUTORS.rst
  account_financial_discount/readme/DESCRIPTION.rst
  account_financial_discount/readme/ROADMAP.rst
  account_financial_discount/readme/USAGE.rst
  account_financial_discount/tests/__init__.py
  account_financial_discount/tests/common.py
  account_financial_discount/tests/test_financial_discount_manual_payment.py
  account_financial_discount/tests/test_financial_discount_reconciliation.py
  account_financial_discount/tests/test_payment_term.py
  account_financial_discount/views/account_move.xml
  account_financial_discount/views/account_reconcile_model.xml
  account_financial_discount/views/payment_receipt.xml
  account_financial_discount/views/payment_term_form.xml
  account_financial_discount/views/res_config_settings.xml
  account_financial_discount/wizard/__init__.py
  account_financial_discount/wizard/account_payment_register.py
  account_financial_discount/wizard/account_payment_register.xml
  setup/account_financial_discount/odoo/addons/account_financial_discount
  setup/account_financial_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#545 [ADD] account_payment_notification: tell people about sent payments
  account_payment_notification/README.rst
  account_payment_notification/__init__.py
  account_payment_notification/__manifest__.py
  account_payment_notification/data/mail_template.xml
  account_payment_notification/data/sms_template.xml
  account_payment_notification/i18n/account_payment_notification.pot
  account_payment_notification/i18n/es.po
  account_payment_notification/models/__init__.py
  account_payment_notification/models/account_payment.py
  account_payment_notification/models/res_company.py
  account_payment_notification/readme/CONFIGURE.rst
  account_payment_notification/readme/CONTRIBUTORS.rst
  account_payment_notification/readme/DESCRIPTION.rst
  account_payment_notification/readme/ROADMAP.rst
  account_payment_notification/readme/USAGE.rst
  account_payment_notification/security/sms_template.xml
  account_payment_notification/static/description/icon.png
  account_payment_notification/static/description/index.html
  account_payment_notification/tests/__init__.py
  account_payment_notification/tests/test_notifications.py
  account_payment_notification/views/account_payment_views.xml
  account_payment_notification/wizards/__init__.py
  account_payment_notification/wizards/res_config_settings.py
  account_payment_notification/wizards/res_config_settings_views.xml
  setup/account_payment_notification/odoo/addons/account_payment_notification
  setup/account_payment_notification/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#515 [14.0][FIX] account_payment_credit_card: create all lines on batch
  account_payment_credit_card/models/account_move.py
Labels: approved, bot is merging ⏳, stale

#539 [15.0][mig]account_payment_batch_process
  account_payment_batch_process/README.rst
  account_payment_batch_process/__init__.py
  account_payment_batch_process/__manifest__.py
  account_payment_batch_process/i18n/account_payment_batch_process.pot
  account_payment_batch_process/models/__init__.py
  account_payment_batch_process/models/payment_adjustment_reason.py
  account_payment_batch_process/readme/CONTRIBUTORS.rst
  account_payment_batch_process/readme/CREDITS.rst
  account_payment_batch_process/readme/DESCRIPTION.rst
  account_payment_batch_process/readme/HISTORY.rst
  account_payment_batch_process/security/ir.model.access.csv
  account_payment_batch_process/static/description/icon.png
  account_payment_batch_process/static/description/index.html
  account_payment_batch_process/views/account_move.xml
  account_payment_batch_process/views/account_payment.xml
  account_payment_batch_process/wizard/__init__.py
  account_payment_batch_process/wizard/account_payment_register.py
  account_payment_batch_process/wizard/account_payment_register.xml
  account_payment_batch_process/wizard/invoice_payment_line.py
  requirements.txt
  setup/account_payment_batch_process/odoo/addons/account_payment_batch_process
  setup/account_payment_batch_process/setup.py
Labels: approved, bot is merging ⏳

#465 [14.0][IMP] account_due_list: adding remaining days widget
  account_due_list/__manifest__.py
  account_due_list/views/payment_view.xml
Labels: bot is merging ⏳, stale

#441 [14.0][ADD] account_check_payee
  account_check_payee/README.rst
  account_check_payee/__init__.py
  account_check_payee/__manifest__.py
  account_check_payee/hooks.py
  account_check_payee/models/__init__.py
  account_check_payee/models/account_payment.py
  account_check_payee/readme/CONTRIBUTORS.rst
  account_check_payee/readme/DESCRIPTION.rst
  account_check_payee/readme/USAGE.rst
  account_check_payee/static/description/icon.png
  account_check_payee/static/description/index.html
  account_check_payee/views/account_payment_views.xml
  account_check_payee/wizard/__init__.py
  account_check_payee/wizard/account_payment_register.py
  account_check_payee/wizard/account_payment_register_views.xml
  setup/account_check_payee/odoo/addons/account_check_payee
  setup/account_check_payee/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#535 [15.0][MIG] account_due_list_payment_mode: Migration to version 15.0
  account_due_list_payment_mode/README.rst
  account_due_list_payment_mode/__init__.py
  account_due_list_payment_mode/__manifest__.py
  account_due_list_payment_mode/i18n/account_due_list_payment_mode.pot
  account_due_list_payment_mode/i18n/de.po
  account_due_list_payment_mode/i18n/es.po
  account_due_list_payment_mode/i18n/es_AR.po
  account_due_list_payment_mode/i18n/it.po
  account_due_list_payment_mode/readme/CONFIGURE.rst
  account_due_list_payment_mode/readme/CONTRIBUTORS.rst
  account_due_list_payment_mode/readme/DESCRIPTION.rst
  account_due_list_payment_mode/readme/INSTALL.rst
  account_due_list_payment_mode/readme/USAGE.rst
  account_due_list_payment_mode/static/description/icon.png
  account_due_list_payment_mode/static/description/index.html
  account_due_list_payment_mode/views/payment_view.xml
  setup/account_due_list_payment_mode/odoo/addons/account_due_list_payment_mode
  setup/account_due_list_payment_mode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#550 [16.0][MIG] account_due_list: Migration to 16.0
  account_due_list/README.rst
  account_due_list/__init__.py
  account_due_list/__manifest__.py
  account_due_list/i18n/account_due_list.pot
  account_due_list/i18n/bg.po
  account_due_list/i18n/ca.po
  account_due_list/i18n/da.po
  account_due_list/i18n/de.po
  account_due_list/i18n/el_GR.po
  account_due_list/i18n/es.po
  account_due_list/i18n/es_AR.po
  account_due_list/i18n/es_MX.po
  account_due_list/i18n/fi.po
  account_due_list/i18n/fr.po
  account_due_list/i18n/fr_CH.po
  account_due_list/i18n/fr_FR.po
  account_due_list/i18n/hr.po
  account_due_list/i18n/it.po
  account_due_list/i18n/nb.po
  account_due_list/i18n/nl.po
  account_due_list/i18n/pt.po
  account_due_list/i18n/pt_BR.po
  account_due_list/i18n/pt_PT.po
  account_due_list/i18n/sk.po
  account_due_list/i18n/sl.po
  account_due_list/i18n/tr.po
  account_due_list/i18n/zh_CN.po
  account_due_list/init_hook.py
  account_due_list/models/__init__.py
  account_due_list/models/account_move_line.py
  account_due_list/readme/CONFIGURE.rst
  account_due_list/readme/CONTRIBUTORS.rst
  account_due_list/readme/DESCRIPTION.rst
  account_due_list/readme/USAGE.rst
  account_due_list/static/description/icon.png
  account_due_list/static/description/index.html
  account_due_list/views/payment_view.xml
  setup/account_due_list/odoo/addons/account_due_list
  setup/account_due_list/setup.py
Labels: approved, bot is merging ⏳
