Repository OCA/account-payment, pull requests merged in 2023-08, with the labels that each got.

#661 [14.0][FIX] account_payment_paired_internal_transfer: use same date of payment
  account_payment_paired_internal_transfer/models/account_payment.py
Labels: approved, ready to merge, bot is merging ⏳

#572 [14.0][ADD] account_payment_line
  account_payment_line/README.rst
  account_payment_line/__init__.py
  account_payment_line/__manifest__.py
  account_payment_line/hooks.py
  account_payment_line/models/__init__.py
  account_payment_line/models/account_move.py
  account_payment_line/models/account_payment.py
  account_payment_line/models/counterpart_line.py
  account_payment_line/readme/CONTRIBUTORS.rst
  account_payment_line/readme/DESCRIPTION.rst
  account_payment_line/readme/USAGE.rst
  account_payment_line/security/ir.model.access.csv
  account_payment_line/static/description/index.html
  account_payment_line/tests/__init__.py
  account_payment_line/tests/test_account_payment_line.py
  account_payment_line/views/account_payment_views.xml
  account_payment_line_import/README.rst
  account_payment_line_import/__init__.py
  account_payment_line_import/__manifest__.py
  account_payment_line_import/data/import_template.xml
  account_payment_line_import/data/payment_detail.xlsx
  account_payment_line_import/models/__init__.py
  account_payment_line_import/models/account_payment.py
  account_payment_line_import/readme/CONTRIBUTORS.rst
  account_payment_line_import/readme/DESCRIPTION.rst
  account_payment_line_import/readme/USAGE.rst
  account_payment_line_import/static/description/index.html
  account_payment_line_import/views/account_payment_view.xml
  setup/account_payment_line/odoo/addons/account_payment_line
  setup/account_payment_line/setup.py
  setup/account_payment_line_import/odoo/addons/account_payment_line_import
  setup/account_payment_line_import/setup.py
Labels: bot is merging ⏳

#660 16.0 mig-account_payment_notification
  account_payment_notification/README.rst
  account_payment_notification/__init__.py
  account_payment_notification/__manifest__.py
  account_payment_notification/data/mail_template.xml
  account_payment_notification/data/sms_template.xml
  account_payment_notification/i18n/account_payment_notification.pot
  account_payment_notification/i18n/es.po
  account_payment_notification/models/__init__.py
  account_payment_notification/models/account_payment.py
  account_payment_notification/models/res_company.py
  account_payment_notification/readme/CONFIGURE.rst
  account_payment_notification/readme/CONTRIBUTORS.rst
  account_payment_notification/readme/DESCRIPTION.rst
  account_payment_notification/readme/ROADMAP.rst
  account_payment_notification/readme/USAGE.rst
  account_payment_notification/security/sms_template.xml
  account_payment_notification/static/description/icon.png
  account_payment_notification/static/description/index.html
  account_payment_notification/tests/__init__.py
  account_payment_notification/tests/test_notifications.py
  account_payment_notification/views/account_payment_views.xml
  account_payment_notification/wizards/__init__.py
  account_payment_notification/wizards/res_config_settings.py
  account_payment_notification/wizards/res_config_settings_views.xml
  setup/account_payment_notification/odoo/addons/account_payment_notification
  setup/account_payment_notification/setup.py
Labels: approved, bot is merging ⏳

#638 [14.0][IMP] account_due_list_payment: init module
  account_due_list_payment/__init__.py
  account_due_list_payment/__manifest__.py
  account_due_list_payment/models/__init__.py
  account_due_list_payment/models/account_move_line.py
  account_due_list_payment/static/description/icon.png
  account_due_list_payment/tests/__init__.py
  account_due_list_payment/tests/test_action_register_payment.py
  account_due_list_payment/views/account_move_line.xml
  setup/account_due_list_payment/odoo/addons/account_due_list_payment
  setup/account_due_list_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳
