Repository OCA/account-payment, pull requests merged in 2023-10, with the labels that each got.

#642 [15.0][MIG] account_check_report
  account_check_report/README.rst
  account_check_report/__init__.py
  account_check_report/__manifest__.py
  account_check_report/i18n/account_check_report.pot
  account_check_report/i18n/pt.po
  account_check_report/readme/CONTRIBUTORS.rst
  account_check_report/readme/DESCRIPTION.rst
  account_check_report/report/__init__.py
  account_check_report/report/account_check_report.xml
  account_check_report/report/report_helper.py
  account_check_report/static/description/icon.png
  account_check_report/static/description/index.html
  setup/account_check_report/odoo/addons/account_check_report
  setup/account_check_report/setup.py
Labels: approved, bot is merging ⏳

#633 [16.0][MIG] account_due_list_aging_comment: Migration to 16.0
  account_due_list_aging_comment/README.rst
  account_due_list_aging_comment/__init__.py
  account_due_list_aging_comment/__manifest__.py
  account_due_list_aging_comment/i18n/account_due_list_aging_comment.pot
  account_due_list_aging_comment/i18n/de.po
  account_due_list_aging_comment/i18n/es.po
  account_due_list_aging_comment/i18n/es_AR.po
  account_due_list_aging_comment/i18n/it.po
  account_due_list_aging_comment/i18n/pt.po
  account_due_list_aging_comment/i18n/pt_BR.po
  account_due_list_aging_comment/i18n/sl.po
  account_due_list_aging_comment/models/__init__.py
  account_due_list_aging_comment/models/account_move_line.py
  account_due_list_aging_comment/readme/CONTRIBUTORS.rst
  account_due_list_aging_comment/readme/DESCRIPTION.rst
  account_due_list_aging_comment/readme/USAGE.rst
  account_due_list_aging_comment/static/description/icon.png
  account_due_list_aging_comment/static/description/index.html
  account_due_list_aging_comment/views/payment_view.xml
  setup/account_due_list_aging_comment/odoo/addons/account_due_list_aging_comment
  setup/account_due_list_aging_comment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#675 [15.0][IMP] account_payment: test performance improvement
  account_payment_return/tests/test_payment_return.py
  account_payment_return_import/tests/test_import_base.py
  account_payment_return_import/tests/test_import_file.py
  account_payment_return_import/tests/test_import_payment_return.py
  account_payment_return_import_iso20022/tests/test_import_iso20022.py
  account_payment_term_extension/tests/test_account_payment_term_multi_day.py
  account_payment_term_extension/tests/test_payment_term.py
Labels: bot is merging ⏳

#676 [16.0][IMP] account_payment: test performance improvement
  account_payment_return/tests/test_payment_return.py
  account_payment_return_import/tests/test_import_base.py
  account_payment_return_import/tests/test_import_file.py
  account_payment_return_import/tests/test_import_payment_return.py
  account_payment_return_import_iso20022/tests/test_import_iso20022.py
  account_payment_term_extension/tests/test_account_payment_term_multi_day.py
  account_payment_term_extension/tests/test_payment_term.py
Labels: bot is merging ⏳

#672 [ADD]account_due_list_edit_inline: editing name and date inline
  account_due_list_edit_inline/README.rst
  account_due_list_edit_inline/__init__.py
  account_due_list_edit_inline/__manifest__.py
  account_due_list_edit_inline/readme/CONFIGURE.rst
  account_due_list_edit_inline/readme/CONTRIBUTORS.rst
  account_due_list_edit_inline/readme/DESCRIPTION.rst
  account_due_list_edit_inline/readme/USAGE.rst
  account_due_list_edit_inline/static/description/icon.png
  account_due_list_edit_inline/static/description/index.html
  account_due_list_edit_inline/views/payment_view.xml
  setup/account_due_list_edit_inline/odoo/addons/account_due_list_edit_inline
  setup/account_due_list_edit_inline/setup.py
Labels: approved, ready to merge, bot is merging ⏳
