Repository OCA/account-payment, pull requests merged in 2023-04, with the labels that each got.

#604 [14.0][FIX] account_cash_discount_payment
  account_cash_discount_payment/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#623 [15.0][OU][FIX] account_check_printing_report_base: Migration script fails
  account_check_printing_report_base/migrations/15.0.1.0.0/pre-migration.py
Labels: approved

#612 [16.0][MIG] account_payment_promissory_note: Migration to 16.0
  account_payment_promissory_note/README.rst
  account_payment_promissory_note/__init__.py
  account_payment_promissory_note/__manifest__.py
  account_payment_promissory_note/i18n/account_payment_promissory_note.pot
  account_payment_promissory_note/i18n/es.po
  account_payment_promissory_note/models/__init__.py
  account_payment_promissory_note/models/account_abstract_payment.py
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/readme/CONTRIBUTORS.rst
  account_payment_promissory_note/readme/DESCRIPTION.rst
  account_payment_promissory_note/readme/USAGE.rst
  account_payment_promissory_note/static/description/icon.png
  account_payment_promissory_note/static/description/index.html
  account_payment_promissory_note/tests/__init__.py
  account_payment_promissory_note/tests/test_account_payment_promissory_note.py
  account_payment_promissory_note/views/account_payment_invoice_view.xml
  account_payment_promissory_note/views/account_payment_view.xml
  account_payment_promissory_note/wizard/__init__.py
  account_payment_promissory_note/wizard/account_register_payments.py
  setup/account_payment_promissory_note/odoo/addons/account_payment_promissory_note
  setup/account_payment_promissory_note/setup.py
Labels: approved, bot is merging ⏳

#624 [15.0][FIX] account_payment_promissory_note: avoid error when paying vendor bills
  account_payment_promissory_note/wizard/account_register_payments.py
Labels: bot is merging ⏳
