Repository OCA/account-payment, pull requests merged in 2023-05, with the labels that each got.

#563 [13.0][ADD] account_cash_discount_base_sale
  account_cash_discount_base_sale/README.rst
  account_cash_discount_base_sale/__init__.py
  account_cash_discount_base_sale/__manifest__.py
  account_cash_discount_base_sale/models/__init__.py
  account_cash_discount_base_sale/models/account_move.py
  account_cash_discount_base_sale/models/sale_order.py
  account_cash_discount_base_sale/readme/CONTRIBUTORS.rst
  account_cash_discount_base_sale/readme/DESCRIPTION.rst
  account_cash_discount_base_sale/static/description/icon.png
  account_cash_discount_base_sale/static/description/index.html
  account_cash_discount_base_sale/tests/__init__.py
  account_cash_discount_base_sale/tests/test_account_cash_discount_base_sale.py
  setup/account_cash_discount_base_sale/odoo/addons/account_cash_discount_base_sale
  setup/account_cash_discount_base_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#561 [15.0][MIG] account_payment_multi_deduction
  account_payment_multi_deduction/README.rst
  account_payment_multi_deduction/__init__.py
  account_payment_multi_deduction/__manifest__.py
  account_payment_multi_deduction/i18n/account_payment_multi_deduction.pot
  account_payment_multi_deduction/models/__init__.py
  account_payment_multi_deduction/models/account_payment.py
  account_payment_multi_deduction/readme/CONTRIBUTORS.rst
  account_payment_multi_deduction/readme/DESCRIPTION.rst
  account_payment_multi_deduction/readme/HISTORY.rst
  account_payment_multi_deduction/readme/USAGE.rst
  account_payment_multi_deduction/security/ir.model.access.csv
  account_payment_multi_deduction/static/description/icon.png
  account_payment_multi_deduction/static/description/index.html
  account_payment_multi_deduction/tests/__init__.py
  account_payment_multi_deduction/tests/test_payment_multi_deduction.py
  account_payment_multi_deduction/wizard/__init__.py
  account_payment_multi_deduction/wizard/account_payment_deduction.py
  account_payment_multi_deduction/wizard/account_payment_register.py
  account_payment_multi_deduction/wizard/account_payment_register_views.xml
  setup/account_payment_multi_deduction/odoo/addons/account_payment_multi_deduction
  setup/account_payment_multi_deduction/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#578 [14.0][ADD] partner_restrict_payment_acquirer
  partner_restrict_payment_acquirer/README.rst
  partner_restrict_payment_acquirer/__init__.py
  partner_restrict_payment_acquirer/__manifest__.py
  partner_restrict_payment_acquirer/models/__init__.py
  partner_restrict_payment_acquirer/models/payment_acquirer.py
  partner_restrict_payment_acquirer/models/res_partner.py
  partner_restrict_payment_acquirer/readme/DESCRIPTION.rst
  partner_restrict_payment_acquirer/readme/ROADMAP.rst
  partner_restrict_payment_acquirer/readme/USAGE.rst
  partner_restrict_payment_acquirer/tests/__init__.py
  partner_restrict_payment_acquirer/tests/test_payment_acquirer.py
  partner_restrict_payment_acquirer/views/payment_templates.xml
  partner_restrict_payment_acquirer/views/res_partner_views.xml
  setup/partner_restrict_payment_acquirer/odoo/addons/partner_restrict_payment_acquirer
  setup/partner_restrict_payment_acquirer/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#625 [15.0][FIX] account_payment_return_import_iso20022: Restore compatibility with pre-payment orders
  account_payment_return_import_iso20022/models/payment_return.py
Labels: bot is merging ⏳

#605 [14.0][IMP] account_due_list: date_maturity asc order in tree view
  account_due_list/views/payment_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#619 [16.0][MIG] account_due_list_payment_mode: Migration to version 16.0
  account_due_list_payment_mode/README.rst
  account_due_list_payment_mode/__init__.py
  account_due_list_payment_mode/__manifest__.py
  account_due_list_payment_mode/i18n/account_due_list_payment_mode.pot
  account_due_list_payment_mode/i18n/de.po
  account_due_list_payment_mode/i18n/es.po
  account_due_list_payment_mode/i18n/es_AR.po
  account_due_list_payment_mode/i18n/it.po
  account_due_list_payment_mode/readme/CONFIGURE.rst
  account_due_list_payment_mode/readme/CONTRIBUTORS.rst
  account_due_list_payment_mode/readme/DESCRIPTION.rst
  account_due_list_payment_mode/readme/INSTALL.rst
  account_due_list_payment_mode/readme/USAGE.rst
  account_due_list_payment_mode/static/description/icon.png
  account_due_list_payment_mode/static/description/index.html
  account_due_list_payment_mode/views/payment_view.xml
  setup/account_due_list_payment_mode/odoo/addons/account_due_list_payment_mode
  setup/account_due_list_payment_mode/setup.py
Labels: approved, bot is merging ⏳

#627 [14.0][MIG] account_check_printing_report_base
  account_check_printing_report_base/README.rst
  account_check_printing_report_base/__init__.py
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/data/report_paperformat.xml
  account_check_printing_report_base/i18n/account_check_printing_report_base.pot
  account_check_printing_report_base/i18n/es.po
  account_check_printing_report_base/i18n/pt.po
  account_check_printing_report_base/models/__init__.py
  account_check_printing_report_base/models/account_journal.py
  account_check_printing_report_base/models/account_payment.py
  account_check_printing_report_base/models/res_company.py
  account_check_printing_report_base/readme/CONFIGURE.rst
  account_check_printing_report_base/readme/CONTRIBUTORS.rst
  account_check_printing_report_base/readme/DESCRIPTION.rst
  account_check_printing_report_base/readme/ROADMAP.rst
  account_check_printing_report_base/readme/USAGE.rst
  account_check_printing_report_base/report/__init__.py
  account_check_printing_report_base/report/account_check_writing_report.xml
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/report/lang.py
  account_check_printing_report_base/security/ir.model.access.csv
  account_check_printing_report_base/static/description/icon.png
  account_check_printing_report_base/static/description/index.html
  account_check_printing_report_base/tests/__init__.py
  account_check_printing_report_base/tests/test_check_printing_report.py
  account_check_printing_report_base/tests/test_num2words_lang_solution.py
  account_check_printing_report_base/views/account_journal_view.xml
  account_check_printing_report_base/views/report_check_base.xml
  setup/account_check_printing_report_base/odoo/addons/account_check_printing_report_base
  setup/account_check_printing_report_base/setup.py
Labels: approved, bot is merging ⏳

#630 [14.0][MIG] account_check_printing_report_sslm102
  account_check_printing_report_sslm102/README.rst
  account_check_printing_report_sslm102/__init__.py
  account_check_printing_report_sslm102/__manifest__.py
  account_check_printing_report_sslm102/data/report_paperformat.xml
  account_check_printing_report_sslm102/data/report_paperformat_parameter.xml
  account_check_printing_report_sslm102/i18n/account_check_printing_report_sslm102.pot
  account_check_printing_report_sslm102/i18n/pt.po
  account_check_printing_report_sslm102/models/__init__.py
  account_check_printing_report_sslm102/models/account_journal.py
  account_check_printing_report_sslm102/models/res_company.py
  account_check_printing_report_sslm102/readme/CONFIGURE.rst
  account_check_printing_report_sslm102/readme/CONTRIBUTORS.rst
  account_check_printing_report_sslm102/readme/DESCRIPTION.rst
  account_check_printing_report_sslm102/readme/INSTALL.rst
  account_check_printing_report_sslm102/readme/USAGE.rst
  account_check_printing_report_sslm102/report/__init__.py
  account_check_printing_report_sslm102/report/account_check_writing_report.xml
  account_check_printing_report_sslm102/report/check_print.py
  account_check_printing_report_sslm102/static/description/icon.png
  account_check_printing_report_sslm102/static/description/index.html
  account_check_printing_report_sslm102/views/report_check.xml
  setup/account_check_printing_report_sslm102/odoo/addons/account_check_printing_report_sslm102
  setup/account_check_printing_report_sslm102/setup.py
Labels: approved, ready to merge, bot is merging ⏳
