Repository OCA/account-payment, pull requests merged in 2024-01, with the labels that each got.

#682 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_payment_return/i18n/account_payment_return.pot
Labels: help wanted, needs review

#694 [15.0] Update from template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  account_check_printing_report_sslm102/views/report_check.xml
Labels: bot is merging ⏳

#671 [15.0][MIG] account_check_payee
  account_check_payee/README.rst
  account_check_payee/__init__.py
  account_check_payee/__manifest__.py
  account_check_payee/hooks.py
  account_check_payee/i18n/account_check_payee.pot
  account_check_payee/models/__init__.py
  account_check_payee/models/account_payment.py
  account_check_payee/readme/CONTRIBUTORS.rst
  account_check_payee/readme/DESCRIPTION.rst
  account_check_payee/readme/USAGE.rst
  account_check_payee/static/description/icon.png
  account_check_payee/static/description/index.html
  account_check_payee/views/account_payment_views.xml
  account_check_payee/wizard/__init__.py
  account_check_payee/wizard/account_payment_register.py
  account_check_payee/wizard/account_payment_register_views.xml
  setup/account_check_payee/odoo/addons/account_check_payee
  setup/account_check_payee/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#696 [15.0][MIG] account_check_date
  account_check_date/README.rst
  account_check_date/__init__.py
  account_check_date/__manifest__.py
  account_check_date/hooks.py
  account_check_date/i18n/account_check_date.pot
  account_check_date/models/__init__.py
  account_check_date/models/account_payment.py
  account_check_date/readme/CONTRIBUTORS.rst
  account_check_date/readme/DESCRIPTION.rst
  account_check_date/readme/USAGE.rst
  account_check_date/static/description/icon.png
  account_check_date/static/description/index.html
  account_check_date/views/account_payment_views.xml
  account_check_date/wizard/__init__.py
  account_check_date/wizard/account_payment_register.py
  account_check_date/wizard/account_payment_register_views.xml
  setup/account_check_date/odoo/addons/account_check_date
  setup/account_check_date/setup.py
Labels: approved, bot is merging ⏳
