Repository OCA/account-payment, pull requests merged in 2024-07, with the labels that each got.

#743 [16.0] [MIG] account_cash_invoice: Migration to 16.0
  account_cash_invoice/README.rst
  account_cash_invoice/__init__.py
  account_cash_invoice/__manifest__.py
  account_cash_invoice/i18n/account_cash_invoice.pot
  account_cash_invoice/i18n/es.po
  account_cash_invoice/i18n/es_PA.po
  account_cash_invoice/i18n/hr.po
  account_cash_invoice/i18n/pt.po
  account_cash_invoice/models/__init__.py
  account_cash_invoice/models/account_bank_statement_line.py
  account_cash_invoice/readme/CONTRIBUTORS.rst
  account_cash_invoice/readme/DESCRIPTION.rst
  account_cash_invoice/readme/ROADMAP.rst
  account_cash_invoice/readme/USAGE.rst
  account_cash_invoice/security/ir.model.access.csv
  account_cash_invoice/static/description/icon.png
  account_cash_invoice/static/description/index.html
  account_cash_invoice/tests/__init__.py
  account_cash_invoice/tests/test_pay_invoice.py
  account_cash_invoice/views/account_journal_dashboard_view.xml
  account_cash_invoice/wizard/__init__.py
  account_cash_invoice/wizard/cash_pay_invoice.py
  account_cash_invoice/wizard/cash_pay_invoice.xml
  setup/account_cash_invoice/odoo/addons/account_cash_invoice
  setup/account_cash_invoice/setup.py
Labels: approved, bot is merging ⏳

#747 [16.0][FIX] account_cash_invoice: Do not create account for test
  account_cash_invoice/tests/test_pay_invoice.py
Labels: bot is merging ⏳

#748 [16.0][FIX] account_cash_invoice: Filter only lines not reconciled
  account_cash_invoice/wizard/cash_pay_invoice.py
Labels: bot is merging ⏳

#709 [ADD] account_move_line_payment: simple partial overdue payment flow
  account_move_line_payment/README.rst
  account_move_line_payment/__init__.py
  account_move_line_payment/__manifest__.py
  account_move_line_payment/i18n/account_move_line_payment.pot
  account_move_line_payment/i18n/es.po
  account_move_line_payment/models/__init__.py
  account_move_line_payment/models/account_move_line.py
  account_move_line_payment/readme/CONFIGURE.md
  account_move_line_payment/readme/CONTEXT.md
  account_move_line_payment/readme/CONTRIBUTORS.md
  account_move_line_payment/readme/CREDITS.md
  account_move_line_payment/readme/DESCRIPTION.md
  account_move_line_payment/readme/ROADMAP.md
  account_move_line_payment/readme/USAGE.md
  account_move_line_payment/static/description/icon.png
  account_move_line_payment/static/description/index.html
  account_move_line_payment/views/account_move_line_view.xml
  setup/account_move_line_payment/odoo/addons/account_move_line_payment
  setup/account_move_line_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#750 [17.0][MIG] account_due_list_payment_mode: Migration to version 17.0
  account_due_list_payment_mode/README.rst
  account_due_list_payment_mode/__init__.py
  account_due_list_payment_mode/__manifest__.py
  account_due_list_payment_mode/i18n/account_due_list_payment_mode.pot
  account_due_list_payment_mode/i18n/de.po
  account_due_list_payment_mode/i18n/es.po
  account_due_list_payment_mode/i18n/es_AR.po
  account_due_list_payment_mode/i18n/it.po
  account_due_list_payment_mode/i18n/pt_BR.po
  account_due_list_payment_mode/pyproject.toml
  account_due_list_payment_mode/readme/CONFIGURE.md
  account_due_list_payment_mode/readme/CONTRIBUTORS.md
  account_due_list_payment_mode/readme/DESCRIPTION.md
  account_due_list_payment_mode/readme/INSTALL.md
  account_due_list_payment_mode/readme/USAGE.md
  account_due_list_payment_mode/static/description/icon.png
  account_due_list_payment_mode/static/description/index.html
  account_due_list_payment_mode/views/payment_view.xml
Labels: approved, bot is merging ⏳

#752 [17.0][MIG] account_payment_return: Migration to version 17.0
  account_payment_return/README.rst
  account_payment_return/__init__.py
  account_payment_return/__manifest__.py
  account_payment_return/data/ir_sequence_data.xml
  account_payment_return/i18n/account_payment_return.pot
  account_payment_return/i18n/am.po
  account_payment_return/i18n/ar.po
  account_payment_return/i18n/bg.po
  account_payment_return/i18n/ca.po
  account_payment_return/i18n/cs.po
  account_payment_return/i18n/de.po
  account_payment_return/i18n/el_GR.po
  account_payment_return/i18n/es.po
  account_payment_return/i18n/es_AR.po
  account_payment_return/i18n/es_CR.po
  account_payment_return/i18n/es_EC.po
  account_payment_return/i18n/es_ES.po
  account_payment_return/i18n/es_MX.po
  account_payment_return/i18n/es_VE.po
  account_payment_return/i18n/et.po
  account_payment_return/i18n/fi.po
  account_payment_return/i18n/fr.po
  account_payment_return/i18n/gl.po
  account_payment_return/i18n/hr.po
  account_payment_return/i18n/hr_HR.po
  account_payment_return/i18n/it.po
  account_payment_return/i18n/lt.po
  account_payment_return/i18n/nl.po
  account_payment_return/i18n/nl_BE.po
  account_payment_return/i18n/pl.po
  account_payment_return/i18n/pt.po
  account_payment_return/i18n/pt_BR.po
  account_payment_return/i18n/pt_PT.po
  account_payment_return/i18n/ro.po
  account_payment_return/i18n/ru.po
  account_payment_return/i18n/sl.po
  account_payment_return/i18n/th.po
  account_payment_return/i18n/tr.po
  account_payment_return/i18n/vi.po
  account_payment_return/i18n/zh_CN.po
  account_payment_return/models/__init__.py
  account_payment_return/models/account_journal.py
  account_payment_return/models/account_move.py
  account_payment_return/models/payment_return.py
  account_payment_return/models/payment_return_reason.py
  account_payment_return/pyproject.toml
  account_payment_return/readme/CONTRIBUTORS.md
  account_payment_return/readme/DESCRIPTION.md
  account_payment_return/readme/USAGE.md
  account_payment_return/security/account_payment_return_security.xml
  account_payment_return/security/ir.model.access.csv
  account_payment_return/static/description/icon.png
  account_payment_return/static/description/index.html
  account_payment_return/static/src/scss/account_payment_return.scss
  account_payment_return/static/src/xml/account_payment_return.xml
  account_payment_return/tests/__init__.py
  account_payment_return/tests/test_payment_return.py
  account_payment_return/views/account_journal_view.xml
  account_payment_return/views/account_move_views.xml
  account_payment_return/views/payment_return_view.xml
Labels: approved, bot is merging ⏳

#749 [16.0][FIX] account_payment_return: Fix line_ids display on form view
  account_payment_return/views/payment_return_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#754 [17.0][FIX] account_payment_return: Fix line_ids display on form view
  account_payment_return/views/payment_return_view.xml
Labels: bot is merging ⏳
