Repository OCA/account-payment, pull requests merged in 2024-05, with the labels that each got.

#726 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  account_payment_term_extension/tests/test_payment_term.py
Labels: help wanted, needs review, bot is merging ⏳

#693 [FIX] account_payment_widget_amount payment in foreign currency for invoice in the same currency
  account_payment_widget_amount/models/account_move_line.py
  account_payment_widget_amount/tests/test_account_payment_widget_amount.py
Labels: approved, ready to merge, bot is merging ⏳

#699 [14.0][FIX] account_due_list_payment: same group in tree and form
  account_due_list_payment/views/account_move_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#727 [16.0] account_payment_widget_amount: Migration to 16.0
  account_payment_widget_amount/README.rst
  account_payment_widget_amount/__init__.py
  account_payment_widget_amount/__manifest__.py
  account_payment_widget_amount/i18n/account_payment_widget_amount.pot
  account_payment_widget_amount/i18n/ca.po
  account_payment_widget_amount/i18n/pt.po
  account_payment_widget_amount/i18n/pt_BR.po
  account_payment_widget_amount/models/__init__.py
  account_payment_widget_amount/models/account_move_line.py
  account_payment_widget_amount/readme/CONTRIBUTORS.rst
  account_payment_widget_amount/readme/DESCRIPTION.rst
  account_payment_widget_amount/readme/USAGE.rst
  account_payment_widget_amount/static/description/icon.png
  account_payment_widget_amount/static/description/index.html
  account_payment_widget_amount/static/description/payment_widget.png
  account_payment_widget_amount/static/description/payment_widget_amount_reconciled.png
  account_payment_widget_amount/static/src/js/account_payment_field.esm.js
  account_payment_widget_amount/static/src/xml/account_payment.xml
  account_payment_widget_amount/tests/__init__.py
  account_payment_widget_amount/tests/test_account_payment_widget_amount.py
  setup/account_payment_widget_amount/odoo/addons/account_payment_widget_amount
  setup/account_payment_widget_amount/setup.py
Labels: bot is merging ⏳

#730 [15.0][IMP] account_payment_return: Set partner in counterpart if only one
  account_payment_return/models/payment_return.py
Labels: approved, bot is merging ⏳
