Repository OCA/account-payment, pull requests merged in 2024-06, with the labels that each got.

#593 [13.0][MIG] partner_restrict_payment_acquirer
  partner_restrict_payment_acquirer/README.rst
  partner_restrict_payment_acquirer/__init__.py
  partner_restrict_payment_acquirer/__manifest__.py
  partner_restrict_payment_acquirer/i18n/partner_restrict_payment_acquirer.pot
  partner_restrict_payment_acquirer/models/__init__.py
  partner_restrict_payment_acquirer/models/payment_acquirer.py
  partner_restrict_payment_acquirer/models/res_partner.py
  partner_restrict_payment_acquirer/readme/DESCRIPTION.rst
  partner_restrict_payment_acquirer/readme/ROADMAP.rst
  partner_restrict_payment_acquirer/readme/USAGE.rst
  partner_restrict_payment_acquirer/static/description/icon.png
  partner_restrict_payment_acquirer/static/description/index.html
  partner_restrict_payment_acquirer/tests/__init__.py
  partner_restrict_payment_acquirer/tests/test_payment_acquirer.py
  partner_restrict_payment_acquirer/views/payment_templates.xml
  partner_restrict_payment_acquirer/views/res_partner_views.xml
  setup/partner_restrict_payment_acquirer/odoo/addons/partner_restrict_payment_acquirer
  setup/partner_restrict_payment_acquirer/setup.py
Labels: approved, ready to merge, bot is merging ⏳, no stale

#735 [14.0][IMP] account_payment_batch_process: clean wizard layout
  account_payment_batch_process/wizard/account_payment_register.xml
Labels: approved, bot is merging ⏳

#737 [16.0][MIG] account_payment_term_discount Migration to V16.0
  account_payment_term_discount/README.rst
  account_payment_term_discount/__init__.py
  account_payment_term_discount/__manifest__.py
  account_payment_term_discount/changes.txt
  account_payment_term_discount/i18n/account_cash_discount_61.pot
  account_payment_term_discount/i18n/account_payment_term_discount.pot
  account_payment_term_discount/i18n/de.po
  account_payment_term_discount/i18n/es_AR.po
  account_payment_term_discount/i18n/fr_FR.po
  account_payment_term_discount/models/__init__.py
  account_payment_term_discount/models/account_move.py
  account_payment_term_discount/models/account_payment_term.py
  account_payment_term_discount/models/product_template.py
  account_payment_term_discount/readme/CONFIGURE.rst
  account_payment_term_discount/readme/CONTRIBUTORS.rst
  account_payment_term_discount/readme/CREDITS.rst
  account_payment_term_discount/readme/DESCRIPTION.rst
  account_payment_term_discount/readme/USAGE.rst
  account_payment_term_discount/security/ir.model.access.csv
  account_payment_term_discount/static/description/icon.png
  account_payment_term_discount/static/description/index.html
  account_payment_term_discount/tests/__init__.py
  account_payment_term_discount/tests/test_customer_payment_term.py
  account_payment_term_discount/views/account_move_view.xml
  account_payment_term_discount/views/account_payment_term_view.xml
  account_payment_term_discount/views/product_view.xml
  account_payment_term_discount/wizard/__init__.py
  account_payment_term_discount/wizard/account_payment_register.py
  account_payment_term_discount/wizard/account_payment_register.xml
  setup/account_payment_term_discount/odoo/addons/account_payment_term_discount
  setup/account_payment_term_discount/setup.py
Labels: bot is merging ⏳

#666 [16.0][MIG] account_payment_line: Migration to 16.0
  account_payment_line/README.rst
  account_payment_line/__init__.py
  account_payment_line/__manifest__.py
  account_payment_line/hooks.py
  account_payment_line/i18n/account_payment_line.pot
  account_payment_line/models/__init__.py
  account_payment_line/models/account_move.py
  account_payment_line/models/account_payment.py
  account_payment_line/models/counterpart_line.py
  account_payment_line/readme/CONTRIBUTORS.rst
  account_payment_line/readme/DESCRIPTION.rst
  account_payment_line/readme/USAGE.rst
  account_payment_line/security/ir.model.access.csv
  account_payment_line/static/description/icon.png
  account_payment_line/static/description/index.html
  account_payment_line/tests/__init__.py
  account_payment_line/tests/test_account_payment_line.py
  account_payment_line/views/account_payment_views.xml
  setup/account_payment_line/odoo/addons/account_payment_line
  setup/account_payment_line/setup.py
Labels: bot is merging ⏳

#716 [16.0][mig] account payment batch process, superseed w/ test
  account_payment_batch_process/README.rst
  account_payment_batch_process/__init__.py
  account_payment_batch_process/__manifest__.py
  account_payment_batch_process/i18n/account_payment_batch_process.pot
  account_payment_batch_process/i18n/es.po
  account_payment_batch_process/i18n/fr.po
  account_payment_batch_process/models/__init__.py
  account_payment_batch_process/models/payment_adjustment_reason.py
  account_payment_batch_process/readme/CONTRIBUTORS.rst
  account_payment_batch_process/readme/CREDITS.rst
  account_payment_batch_process/readme/DESCRIPTION.rst
  account_payment_batch_process/readme/HISTORY.rst
  account_payment_batch_process/security/ir.model.access.csv
  account_payment_batch_process/static/description/icon.png
  account_payment_batch_process/static/description/index.html
  account_payment_batch_process/tests/__init__.py
  account_payment_batch_process/tests/test_account_payment_batch_process.py
  account_payment_batch_process/views/account_move.xml
  account_payment_batch_process/views/account_payment.xml
  account_payment_batch_process/wizard/__init__.py
  account_payment_batch_process/wizard/account_payment_register.py
  account_payment_batch_process/wizard/account_payment_register.xml
  account_payment_batch_process/wizard/invoice_payment_line.py
  requirements.txt
  setup/account_payment_batch_process/odoo/addons/account_payment_batch_process
  setup/account_payment_batch_process/setup.py
Labels: approved, bot is merging ⏳

#736 [IMP] account_payment_batch_process: prefer grouping payments per invoice
  account_payment_batch_process/wizard/account_payment_register.py
  account_payment_batch_process/wizard/account_payment_register.xml
Labels: approved, bot is merging ⏳
