Repository OCA/account-payment, pull requests merged in 2025-03, with the labels that each got.

#797 [18.0][ADD] account_payment_tier_validation
  account_payment_tier_validation/README.rst
  account_payment_tier_validation/__init__.py
  account_payment_tier_validation/__manifest__.py
  account_payment_tier_validation/models/__init__.py
  account_payment_tier_validation/models/account_move.py
  account_payment_tier_validation/models/account_payment.py
  account_payment_tier_validation/models/tier_definition.py
  account_payment_tier_validation/pyproject.toml
  account_payment_tier_validation/readme/CONFIGURE.md
  account_payment_tier_validation/readme/CONTRIBUTORS.md
  account_payment_tier_validation/readme/DESCRIPTION.md
  account_payment_tier_validation/readme/INSTALL.md
  account_payment_tier_validation/readme/ROADMAP.md
  account_payment_tier_validation/readme/USAGE.md
  account_payment_tier_validation/static/description/icon.png
  account_payment_tier_validation/static/description/index.html
  account_payment_tier_validation/tests/__init__.py
  account_payment_tier_validation/tests/test_tier_validation.py
  account_payment_tier_validation/views/account_payment_view.xml
Labels: approved, bot is merging ⏳

#807 [16.0][FIX] account_payment_term_extension: Define the appropriate value in some cases
  account_payment_term_extension/models/account_payment_term.py
  account_payment_term_extension/tests/test_account_payment_term_multi_day.py
Labels: bot is merging ⏳

#740 [16.0][FIX] account_payment_batch_process: allow original domain of payment method line
  account_payment_batch_process/wizard/account_payment_register.xml
Labels: approved, bot is merging ⏳

#697 [16.0][MIG] account_payment_batch_process_discount
  account_payment_batch_process_discount/README.rst
  account_payment_batch_process_discount/__init__.py
  account_payment_batch_process_discount/__manifest__.py
  account_payment_batch_process_discount/i18n/account_payment_batch_process_discount.pot
  account_payment_batch_process_discount/models/__init__.py
  account_payment_batch_process_discount/models/account_move.py
  account_payment_batch_process_discount/models/account_payment_term_line.py
  account_payment_batch_process_discount/readme/CONFIGURE.rst
  account_payment_batch_process_discount/readme/CONTRIBUTORS.rst
  account_payment_batch_process_discount/readme/DESCRIPTION.rst
  account_payment_batch_process_discount/readme/USAGE.rst
  account_payment_batch_process_discount/static/description/icon.png
  account_payment_batch_process_discount/static/description/index.html
  account_payment_batch_process_discount/tests/__init__.py
  account_payment_batch_process_discount/tests/test_account_payment_batch_process_discount.py
  account_payment_batch_process_discount/views/account_move.xml
  account_payment_batch_process_discount/wizard/__init__.py
  account_payment_batch_process_discount/wizard/account_payment_register.py
  account_payment_batch_process_discount/wizard/invoice_payment_line.py
  setup/account_payment_batch_process_discount/odoo/addons/account_payment_batch_process_discount
  setup/account_payment_batch_process_discount/setup.py
Labels: approved, bot is merging ⏳

#678 [16.0][MIG] account_payment_line_import
  account_payment_line_import/README.rst
  account_payment_line_import/__init__.py
  account_payment_line_import/__manifest__.py
  account_payment_line_import/data/import_template.xml
  account_payment_line_import/data/payment_detail.xlsx
  account_payment_line_import/i18n/account_payment_line_import.pot
  account_payment_line_import/models/__init__.py
  account_payment_line_import/models/account_payment.py
  account_payment_line_import/readme/CONTRIBUTORS.rst
  account_payment_line_import/readme/DESCRIPTION.rst
  account_payment_line_import/readme/USAGE.rst
  account_payment_line_import/static/description/icon.png
  account_payment_line_import/static/description/index.html
  account_payment_line_import/views/account_payment_view.xml
  setup/account_payment_line_import/odoo/addons/account_payment_line_import
  setup/account_payment_line_import/setup.py
Labels: approved, bot is merging ⏳

#808 [16.0][FIX] account_payment_credit_card + account_cash_invoice: Post-install test + fallback to load CoA
  account_cash_invoice/tests/test_pay_invoice.py
  account_payment_credit_card/tests/test_payment_credit_card.py
Labels: bot is merging ⏳

#798 [MIG] partner_restrict_payment_acquirer: Migration to 17.0
  partner_restrict_payment_acquirer/README.rst
  partner_restrict_payment_acquirer/__init__.py
  partner_restrict_payment_acquirer/__manifest__.py
  partner_restrict_payment_acquirer/i18n/es.po
  partner_restrict_payment_acquirer/i18n/it.po
  partner_restrict_payment_acquirer/i18n/partner_restrict_payment_acquirer.pot
  partner_restrict_payment_acquirer/models/__init__.py
  partner_restrict_payment_acquirer/models/payment_provider.py
  partner_restrict_payment_acquirer/models/res_partner.py
  partner_restrict_payment_acquirer/pyproject.toml
  partner_restrict_payment_acquirer/readme/DESCRIPTION.md
  partner_restrict_payment_acquirer/readme/ROADMAP.md
  partner_restrict_payment_acquirer/readme/USAGE.md
  partner_restrict_payment_acquirer/static/description/icon.png
  partner_restrict_payment_acquirer/static/description/index.html
  partner_restrict_payment_acquirer/tests/__init__.py
  partner_restrict_payment_acquirer/tests/test_payment_provider.py
  partner_restrict_payment_acquirer/views/res_partner_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#741 [16.0][IMP] account_payment_term_discount: add migration script
  account_payment_term_discount/migrations/16.0.1.0.0/post-migration.py
Labels: approved, ready to merge, bot is merging ⏳
