Repository OCA/account-payment, pull requests merged in 2025-02, with the labels that each got.

#783 [18.0][MIG] account_payment_promissory_note: Migration to 18.0
  account_payment_promissory_note/README.rst
  account_payment_promissory_note/__init__.py
  account_payment_promissory_note/__manifest__.py
  account_payment_promissory_note/i18n/account_payment_promissory_note.pot
  account_payment_promissory_note/i18n/es.po
  account_payment_promissory_note/i18n/it.po
  account_payment_promissory_note/models/__init__.py
  account_payment_promissory_note/models/account_abstract_payment.py
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/pyproject.toml
  account_payment_promissory_note/readme/CONTRIBUTORS.md
  account_payment_promissory_note/readme/DESCRIPTION.md
  account_payment_promissory_note/readme/USAGE.md
  account_payment_promissory_note/static/description/icon.png
  account_payment_promissory_note/static/description/index.html
  account_payment_promissory_note/tests/__init__.py
  account_payment_promissory_note/tests/test_account_payment_promissory_note.py
  account_payment_promissory_note/views/account_payment_invoice_view.xml
  account_payment_promissory_note/views/account_payment_view.xml
  account_payment_promissory_note/wizard/__init__.py
  account_payment_promissory_note/wizard/account_register_payments.py
Labels: approved, bot is merging ⏳

#789 [17.0][MIG] account_payment_term_security: Migration to 17.0
  account_payment_term_security/README.rst
  account_payment_term_security/__init__.py
  account_payment_term_security/__manifest__.py
  account_payment_term_security/i18n/account_payment_term_security.pot
  account_payment_term_security/i18n/es.po
  account_payment_term_security/models/__init__.py
  account_payment_term_security/models/account_move.py
  account_payment_term_security/models/res_partner.py
  account_payment_term_security/pyproject.toml
  account_payment_term_security/readme/CONFIGURE.md
  account_payment_term_security/readme/CONTRIBUTORS.md
  account_payment_term_security/readme/DESCRIPTION.md
  account_payment_term_security/security/security.xml
  account_payment_term_security/static/description/icon.png
  account_payment_term_security/static/description/index.html
  account_payment_term_security/tests/__init__.py
  account_payment_term_security/tests/test_account_payment_term_security.py
Labels: approved, bot is merging ⏳

#790 [17.0][MIG] sale_payment_term_security: Migration to 17.0
  sale_payment_term_security/README.rst
  sale_payment_term_security/__init__.py
  sale_payment_term_security/__manifest__.py
  sale_payment_term_security/i18n/es.po
  sale_payment_term_security/i18n/sale_payment_term_security.pot
  sale_payment_term_security/models/__init__.py
  sale_payment_term_security/models/sale_order.py
  sale_payment_term_security/pyproject.toml
  sale_payment_term_security/readme/CONFIGURE.md
  sale_payment_term_security/readme/CONTRIBUTORS.md
  sale_payment_term_security/readme/DESCRIPTION.md
  sale_payment_term_security/static/description/icon.png
  sale_payment_term_security/static/description/index.html
  sale_payment_term_security/tests/__init__.py
  sale_payment_term_security/tests/test_sale_payment_term_security.py
Labels: approved, bot is merging ⏳

#765 [18.0][MIG] account_due_list: Migration to 18.0
  account_due_list/README.rst
  account_due_list/__init__.py
  account_due_list/__manifest__.py
  account_due_list/i18n/account_due_list.pot
  account_due_list/i18n/bg.po
  account_due_list/i18n/ca.po
  account_due_list/i18n/da.po
  account_due_list/i18n/de.po
  account_due_list/i18n/el_GR.po
  account_due_list/i18n/es.po
  account_due_list/i18n/es_AR.po
  account_due_list/i18n/es_MX.po
  account_due_list/i18n/fi.po
  account_due_list/i18n/fr.po
  account_due_list/i18n/fr_CH.po
  account_due_list/i18n/fr_FR.po
  account_due_list/i18n/hr.po
  account_due_list/i18n/it.po
  account_due_list/i18n/nb.po
  account_due_list/i18n/nl.po
  account_due_list/i18n/pt.po
  account_due_list/i18n/pt_BR.po
  account_due_list/i18n/pt_PT.po
  account_due_list/i18n/sk.po
  account_due_list/i18n/sl.po
  account_due_list/i18n/tr.po
  account_due_list/i18n/zh_CN.po
  account_due_list/init_hook.py
  account_due_list/models/__init__.py
  account_due_list/models/account_move_line.py
  account_due_list/pyproject.toml
  account_due_list/readme/CONFIGURE.md
  account_due_list/readme/CONTRIBUTORS.md
  account_due_list/readme/DESCRIPTION.md
  account_due_list/readme/USAGE.md
  account_due_list/static/description/icon.png
  account_due_list/static/description/index.html
  account_due_list/tests/__init__.py
  account_due_list/tests/test_account_due_list.py
  account_due_list/views/payment_view.xml
Labels: bot is merging ⏳, stale

#795 [15.0][MIG] partner_restrict_payment_acquirer: Migration to 15.0
  partner_restrict_payment_acquirer/README.rst
  partner_restrict_payment_acquirer/__init__.py
  partner_restrict_payment_acquirer/__manifest__.py
  partner_restrict_payment_acquirer/i18n/es.po
  partner_restrict_payment_acquirer/i18n/it.po
  partner_restrict_payment_acquirer/i18n/partner_restrict_payment_acquirer.pot
  partner_restrict_payment_acquirer/models/__init__.py
  partner_restrict_payment_acquirer/models/payment_acquirer.py
  partner_restrict_payment_acquirer/models/res_partner.py
  partner_restrict_payment_acquirer/readme/CONTRIBUTORS.rst
  partner_restrict_payment_acquirer/readme/DESCRIPTION.rst
  partner_restrict_payment_acquirer/readme/USAGE.rst
  partner_restrict_payment_acquirer/static/description/icon.png
  partner_restrict_payment_acquirer/static/description/index.html
  partner_restrict_payment_acquirer/tests/__init__.py
  partner_restrict_payment_acquirer/tests/test_payment_acquirer.py
  partner_restrict_payment_acquirer/views/payment_templates.xml
  partner_restrict_payment_acquirer/views/res_partner_views.xml
  setup/partner_restrict_payment_acquirer/odoo/addons/partner_restrict_payment_acquirer
  setup/partner_restrict_payment_acquirer/setup.py
Labels: approved, bot is merging ⏳

#799 [18.0][MIG] account_check_printing_report_base: Migration to 18.0
  account_check_printing_report_base/README.rst
  account_check_printing_report_base/__init__.py
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/data/report_paperformat.xml
  account_check_printing_report_base/i18n/account_check_printing_report_base.pot
  account_check_printing_report_base/i18n/es.po
  account_check_printing_report_base/i18n/pt.po
  account_check_printing_report_base/migrations/18.0.1.0.0/pre-migration.py
  account_check_printing_report_base/models/__init__.py
  account_check_printing_report_base/models/account_journal.py
  account_check_printing_report_base/models/account_payment.py
  account_check_printing_report_base/models/res_company.py
  account_check_printing_report_base/pyproject.toml
  account_check_printing_report_base/readme/CONFIGURE.md
  account_check_printing_report_base/readme/CONTRIBUTORS.md
  account_check_printing_report_base/readme/DESCRIPTION.md
  account_check_printing_report_base/readme/ROADMAP.md
  account_check_printing_report_base/readme/USAGE.md
  account_check_printing_report_base/report/__init__.py
  account_check_printing_report_base/report/account_check_writing_report.xml
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/report/lang.py
  account_check_printing_report_base/security/ir.model.access.csv
  account_check_printing_report_base/static/description/icon.png
  account_check_printing_report_base/static/description/index.html
  account_check_printing_report_base/tests/__init__.py
  account_check_printing_report_base/tests/test_check_printing_report.py
  account_check_printing_report_base/tests/test_num2words_lang_solution.py
  account_check_printing_report_base/views/account_journal_view.xml
  account_check_printing_report_base/views/report_check_base.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#725 [16.0][MIG] account_check_printing_report_base
  account_check_printing_report_base/README.rst
  account_check_printing_report_base/__init__.py
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/data/report_paperformat.xml
  account_check_printing_report_base/i18n/account_check_printing_report_base.pot
  account_check_printing_report_base/i18n/es.po
  account_check_printing_report_base/i18n/pt.po
  account_check_printing_report_base/models/__init__.py
  account_check_printing_report_base/models/account_journal.py
  account_check_printing_report_base/models/account_payment.py
  account_check_printing_report_base/models/res_company.py
  account_check_printing_report_base/readme/CONFIGURE.rst
  account_check_printing_report_base/readme/CONTRIBUTORS.rst
  account_check_printing_report_base/readme/DESCRIPTION.rst
  account_check_printing_report_base/readme/ROADMAP.rst
  account_check_printing_report_base/readme/USAGE.rst
  account_check_printing_report_base/report/__init__.py
  account_check_printing_report_base/report/account_check_writing_report.xml
  account_check_printing_report_base/report/check_print.py
  account_check_printing_report_base/report/lang.py
  account_check_printing_report_base/security/ir.model.access.csv
  account_check_printing_report_base/static/description/icon.png
  account_check_printing_report_base/static/description/index.html
  account_check_printing_report_base/tests/__init__.py
  account_check_printing_report_base/tests/test_check_printing_report.py
  account_check_printing_report_base/tests/test_num2words_lang_solution.py
  account_check_printing_report_base/views/account_journal_view.xml
  account_check_printing_report_base/views/report_check_base.xml
  setup/account_check_printing_report_base/odoo/addons/account_check_printing_report_base
  setup/account_check_printing_report_base/setup.py
Labels: approved, bot is merging ⏳

#802 [16.0][FIX] account_payment_term_extension: Post-install test + fallback to load CoA
  account_payment_term_extension/tests/test_account_payment_term_multi_day.py
  account_payment_term_extension/tests/test_payment_term.py
Labels: bot is merging ⏳
