Repository OCA/account-payment, pull requests merged in 2025-01, with the labels that each got.

#782 [15.0][IMP] account_check_printing_report_base: Remove unnecessary dependency
  account_check_printing_report_base/__manifest__.py
  account_check_printing_report_base/static/description/index.html
  account_check_printing_report_dlt103/__manifest__.py
  account_check_printing_report_dlt103/static/description/index.html
  account_check_printing_report_sslm102/__manifest__.py
  account_check_printing_report_sslm102/static/description/index.html
Labels: approved, bot is merging ⏳

#770 [14.0][BCKP] account_payment_promissory_note: Backport to 14.0
  account_payment_promissory_note/README.rst
  account_payment_promissory_note/__init__.py
  account_payment_promissory_note/__manifest__.py
  account_payment_promissory_note/i18n/account_payment_promissory_note.pot
  account_payment_promissory_note/i18n/es.po
  account_payment_promissory_note/models/__init__.py
  account_payment_promissory_note/models/account_abstract_payment.py
  account_payment_promissory_note/models/account_payment.py
  account_payment_promissory_note/readme/CONTRIBUTORS.rst
  account_payment_promissory_note/readme/DESCRIPTION.rst
  account_payment_promissory_note/readme/USAGE.rst
  account_payment_promissory_note/static/description/icon.png
  account_payment_promissory_note/static/description/index.html
  account_payment_promissory_note/tests/__init__.py
  account_payment_promissory_note/tests/test_account_payment_promissory_note.py
  account_payment_promissory_note/views/account_payment_invoice_view.xml
  account_payment_promissory_note/views/account_payment_view.xml
  account_payment_promissory_note/wizard/__init__.py
  account_payment_promissory_note/wizard/account_register_payments.py
  setup/account_payment_promissory_note/odoo/addons/account_payment_promissory_note
  setup/account_payment_promissory_note/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#787 [16.0][IMP] account_due_list: Avoid same priority than account.view_move_line_pivot
  account_due_list/views/payment_view.xml
Labels: bot is merging ⏳
