Repository OCA/account-payment, pull requests merged in 2025-09, with the labels that each got.

#875 [18.0][FIX] account_payment_return_import: payment_returns domain typo
  account_payment_return_import/wizard/payment_return_import.py
Labels: bot is merging ⏳

#855 [18.0][MIG] account_voucher_killer: Migration to 18.0
  account_voucher_killer/README.rst
  account_voucher_killer/__init__.py
  account_voucher_killer/__manifest__.py
  account_voucher_killer/i18n/account_voucher_killer.pot
  account_voucher_killer/i18n/ca_ES.po
  account_voucher_killer/i18n/es.po
  account_voucher_killer/i18n/fr.po
  account_voucher_killer/i18n/pt_BR.po
  account_voucher_killer/i18n/sl.po
  account_voucher_killer/pyproject.toml
  account_voucher_killer/readme/CONFIGURE.md
  account_voucher_killer/readme/CONTRIBUTORS.md
  account_voucher_killer/readme/DESCRIPTION.md
  account_voucher_killer/security/invoice_data.xml
  account_voucher_killer/static/description/icon.png
  account_voucher_killer/static/description/index.html
  account_voucher_killer/view/invoice_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#874 [18.0][IMP] - support Camt 053 in account_payment_return_import_iso20022
  account_payment_return_import_iso20022/readme/CONTRIBUTORS.md
  account_payment_return_import_iso20022/readme/DESCRIPTION.md
  account_payment_return_import_iso20022/tests/test_files/test-sepa-camt-053-unpaid.xml
  account_payment_return_import_iso20022/tests/test_files/test-sepa-camt-054-unpaid.xml
  account_payment_return_import_iso20022/tests/test_import_iso20022.py
  account_payment_return_import_iso20022/wizard/camt_parser.py
Labels: bot is merging ⏳

#775 [16.0][ADD] payment_partner
  payment_partner/README.rst
  payment_partner/__init__.py
  payment_partner/__manifest__.py
  payment_partner/models/__init__.py
  payment_partner/models/payment_provider.py
  payment_partner/readme/CONTRIBUTORS.md
  payment_partner/readme/DESCRIPTION.md
  payment_partner/readme/USAGE.md
  payment_partner/static/description/icon.png
  payment_partner/static/description/index.html
  payment_partner/tests/__init__.py
  payment_partner/tests/test_payment_partner.py
  payment_partner/views/payment_provider.xml
  setup/payment_partner/odoo/addons/payment_partner
  setup/payment_partner/setup.py
Labels: approved, bot is merging ⏳
