Repository OCA/account-payment, pull requests merged in 2025-04, with the labels that each got.

#745 [17.0][MIG] account_payment_widget_amount: Migration to 17.0
  account_payment_widget_amount/README.rst
  account_payment_widget_amount/__init__.py
  account_payment_widget_amount/__manifest__.py
  account_payment_widget_amount/i18n/account_payment_widget_amount.pot
  account_payment_widget_amount/i18n/ca.po
  account_payment_widget_amount/i18n/it.po
  account_payment_widget_amount/i18n/pt.po
  account_payment_widget_amount/i18n/pt_BR.po
  account_payment_widget_amount/models/__init__.py
  account_payment_widget_amount/models/account_move_line.py
  account_payment_widget_amount/pyproject.toml
  account_payment_widget_amount/readme/CONTRIBUTORS.md
  account_payment_widget_amount/readme/DESCRIPTION.md
  account_payment_widget_amount/readme/USAGE.md
  account_payment_widget_amount/static/description/icon.png
  account_payment_widget_amount/static/description/index.html
  account_payment_widget_amount/static/description/payment_widget.png
  account_payment_widget_amount/static/description/payment_widget_amount_reconciled.png
  account_payment_widget_amount/static/src/js/account_payment_field.esm.js
  account_payment_widget_amount/static/src/xml/account_payment.xml
  account_payment_widget_amount/tests/__init__.py
  account_payment_widget_amount/tests/test_account_payment_widget_amount.py
Labels: bot is merging ⏳

#778 [16.0][IMP] account_payment_return: Use _get_all_reconciled_invoice_partials method to simplify
  account_payment_return/models/account_move.py
  account_payment_return/models/payment_return.py
  account_payment_return/static/src/xml/account_payment_return.xml
Labels: approved, bot is merging ⏳, stale

#819 [18.0][FIX] account_payment_tier_validation: fix incorrect validation_status assertion in test
  account_payment_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳
